### ISSUE TITLE
Adjust the search bar header

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#100]
Adjust the search bar header to be "Search the Archives and Request Materials"

*This change should be made on all pages where the search bar appears.  Note that on the repository pages, the text should be "Search this Repository and Request Materials"

**Comment by maxdmayhew** [comment]
![Screen Shot 2023-03-02 at 1.50.48 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/57739473-3210-4021-8901-cad4eda75fdc)

![Screen Shot 2023-03-02 at 1.51.05 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/f31679cf-b1c7-4dd7-800d-6709c1862874)

![Screen Shot 2023-03-02 at 1.51.20 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/2e34d155-b3fa-4de1-bb3e-59cf76f70a73)

updated and PR pending

**Comment by maxdmayhew** [comment]
![Screen Shot 2023-03-02 at 2.12.05 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/d2ab5ad2-56d1-4574-977c-f174df959416)

![Screen Shot 2023-03-02 at 2.13.01 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/c1a963c1-7f38-44f8-99c3-5923da8dceb2)

updated
