### ISSUE TITLE
Deploy local plug-ins and code-based (non-UI-set) configurations over to the ASpace production instance. 

### ISSUE THREAD

**Issue by tmill29** [emory-libraries/aspace#101]
Request a deployment of PUI on May 24 and staff-side plug-ins and configurations to prod following the procedures here: https://github.com/emory-libraries/aspace-deployment .  Please ensure that all integrations (such as Aeon) reference the production environments, not test.

**Comment by maxdmayhew** [comment]
Can we update the readme file to include directions to create and merge the PR before step 6 in the predeploy directions?

**Comment by maxdmayhew** [comment]
deploy email for production has been sent.
