### ISSUE TITLE
Document configurable dropdown menu options

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#109]
ArchivesSpace has a number of dropdown menus that can be customized.  Please create a report of all configurable dropdown menus along with the values currently in each list.  Please also provide information about how to merge/change values.  This report will be sent to the archivists, who will figure out which changes/deletions need to be made.

The [ArchivesSpace manual ]( https://archivesspace.atlassian.net/wiki/spaces/ArchivesSpaceUserManual/overview)has additional information about dropdown menus and how to customize.

**Comment by lisahamlett** [comment]
I have posted the question about how to do this to the basecamp: https://3.basecamp.com/3410311/buckets/29543127/messages/5965328357

**Comment by tmiles2** [comment]
Avery will take the first pass at gather information on where this information lives.

**Comment by avejohnson** [comment]
Per Blake: "I guess in this case the only way to do it will be bad/tedious, and that's to click around and find them all. The code has them scattered and I can't see any way that's easier on the code side. Nothing in the locales or code is called out as "drop down" in any helpful way." 

So it appears that this process will have to be done manually.

**Comment by avejohnson** [comment]
It looks like we can gather the controlled value lists through an API call. Backend team should take over for that.

**Comment by avejohnson** [comment]
https://3.basecamp.com/3410311/buckets/29543127/messages/5965328357

"Just a thought.  By drop-downs, do the archivists by any chance mean the Controlled Value Lists <https://emory-dev.lyrasistechnology.org/staff/enumerations?>  If so, you can pull those through the API.  <https://archivesspace.github.io/archivesspace/api/?shell#list-all-defined-enumerations-as-a-csv.>"

**Comment by erussey** [comment]
Yes, we absolutely mean the above.  This should be reassigned to backend.

**Comment by bwatson78** [comment]
Direct output of API
https://emory-my.sharepoint.com/:x:/g/personal/bwatso9_emory_edu/Ean_OnsQjC5Em6QWKAiEoFMBOw3ivammmdfyc3ExighBSw?e=O6lHw1
