### ISSUE TITLE
Document existing user permissions in ASpace prod.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#110]
Please document the existing user permissions for each repository in ASpace.  Permissions should include the group permission, what permissions that group has, and the users associated with that permission group.

Documentation of out-of-the box permissions structures is available in the [ArchivesSpace manual](https://archivesspace.atlassian.net/wiki/spaces/ArchivesSpaceUserManual/overview).  

A report of the above will meet the requirements of this ticket.  We are trying to document where (if any) custom permissions we have added + which users have each given permission.

**Comment by lisahamlett** [comment]
Here you go: [https://app.zenhub.com/files/531984195/541c6bfe-11bd-4ec4-8cc4-2c0d2f4b1ecb/download](https://app.zenhub.com/files/531984195/541c6bfe-11bd-4ec4-8cc4-2c0d2f4b1ecb/download)
