### ISSUE TITLE
Revise curate integration API script

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#113]
We need to make a few modifications to the curate integration API. See ticket #10 for related work.

Please add:

- Finding aid: This is currently empty and should be populated with the value that is currently populating system_of_record_ID

Please modify:

- system_of_record_id:  This currently points to the discovery system URI.  We need it to point to the backend URI (example: https://emory-dev.lyrasistechnology.org/staff/resources/7185)

- creator: This field should be repeatable. We do not have any examples in the test data currently (though I can create one).

This can be tested on resource 5643 (Matt and Evelyn Crawford papers).

**Comment by abelemlih** [comment]
Based on my conversation with @erussey, the following will be changed:

- `system_of_record_id`: set to `aspace:uri` e.g. `aspace:/repositories/1/resources/1`
- `finding_aid_link`: set to `public_base_url/uri` e.g. `aspace_public_base_url/repositories/1/resources/1`

No changes required for the `creator` field. It is already set correctly.

**Comment by abelemlih** [comment]
PR ready for review: https://github.com/emory-libraries/aspace/issues/113

**Comment by abelemlih** [comment]
@erussey I sent you an email with resources for testing. Let me know if you have any questions!
