### ISSUE TITLE
Management of test/prod deployments and data refresh

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#118]
There was an issue today with a data load where Lyrasis overwrote our custom permissions in Test (https://3.basecamp.com/3410311/buckets/29543127/messages/5965668138).  Their procedure seems to be to run a separate copy of our production instance on their servers, do a data load and then overwrite our test instance.  I'm concerned about the impact of losing all in application configurations (anything set in the UI itself such as permissions, dropdown configs, report templates, etc.)

How will this affect the configuration work we're currently only doing in test? Should we shift the stories in this sprint on reports and permissions to after the final data load?

**Comment by tmill29** [comment]
I will schedule a meeting between Elizabeth, Alex, Collin, myself and Lyrasis.

**Comment by erussey** [comment]
We met with Lyrasis and clarified that code will move from dev to prod while data moves from prod to dev.  Database refreshes from prod will overwrite all local configurations including permissions, drop down menus, custom reports, and anything else that is set in the UI rather than in a plug-in, YML file or config file.  

The plan for moving forward is to do all remaining configurations in prod after the final data load into production.  We may want to consider creating a script to restore test permissions after data refreshes if permissions between prod and test are different.
