### ISSUE TITLE
Create API Users

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/aspace#119]
Rather than creating and maintaining individual user accounts for API access, we should create a couple general API users we can reuse as necessary, and users as needed for inter-application integrations.

In each environment:
- [ ] Create two users for developers: `developer_1_api` and `developer_2_api`. They should have read and write access, and should not have an email address.
- [ ] Create a read-only user for Curate called `curate_api`. It too should not have an email address.

If an email address is necessary, the Sharepoint email for LTDS should be used (Ask @rotated8 )

Afterwards, the credentials for these users should be added to 1Password, so the division can share them.

**Comment by lisahamlett** [comment]
I have created the users, but I am taking a break to get some dinner before I add their permissions because that's going to take a minute.

I have sent the information to Collin and he is going to add them to 1Password.

**Comment by lisahamlett** [comment]
I have added permissions to both production and test.
