### ISSUE TITLE
Develop custom header and apply to all pages in public site.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#12]
Develop standard header to closely match that of Library Search.  It should include the library logo as well as the bar across the top of the page.

Wireframe in comments.

See also [ticket #15](https://app.zenhub.com/workspaces/archivesspace-63122393d517dc001c3ceb07/issues/gh/emory-libraries/aspace/15).  

Links for header:
Home: https://emory-dev.lyrasistechnology.org/
Library Search: https://search.libraries.emory.edu
Aviary: http://aviary.libraries.emory.edu
Emory Digital Collections: https://digital.library.emory.edu/
Browse repositories: https://emory-dev.lyrasistechnology.org/repositories
Browse collections: https://emory-dev.lyrasistechnology.org/repositories/resources
Browse digital materials: https://emory-dev.lyrasistechnology.org/objects?limit=digital_object
Request materials: https://emorytest.aeon.atlas-sys.com
Help (in app link)
Search: https://emory-dev.lyrasistechnology.org/

Please apply new custom header to all pages in public site.

**Comment by CB987** [comment]
You may also want to make changes to the main index page, or the header and footer. Those overrides would go into the following places for the public side of your site:

archivesspace/plugins/local/public/views/welcome/show.html.erb
archivesspace/plugins/local/public/views/shared/_header.html.erb
archivesspace/plugins/local/public/views/shared/_footer.html.erb

**Comment by erussey** [comment]
[https://app.zenhub.com/files/531984195/1d0874fd-027f-418f-99b0-d55c02b36fea/download](https://app.zenhub.com/files/531984195/1d0874fd-027f-418f-99b0-d55c02b36fea/download)

1. Dropdown menu
2. Click on logo returns to ASpace public homepage

**Comment by maxdmayhew** [comment]
![Screen Shot 2023-02-03 at 11.21.03 AM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/ba62c286-8654-4eef-b80c-43f7acc5d9b0)

![Screen Shot 2023-02-03 at 11.22.02 AM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/4bce481b-6aad-4ce0-a4b5-d4e6576cc1ad)

![Screen Shot 2023-02-03 at 11.22.02 AM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/6c46187c-ae0a-44e3-9fd8-a5758edf85ee)

Could I get a bit of clarification on the styling? Do we want the links for the site to live on the side like they do on the main libraries site or will everything live in top nav like it does on search?

**Comment by maxdmayhew** [comment]
The estimate from a 2 to an 8 was changed for a few reasons. I was mistaken and initially thoughts both search and archivespace were both built on the same version of bootstrap. This is not the case. Search uses bootstrap 4 which I is much more flexible and easier to work with, mainly due to its use of flexbox. Archive Space uses bootstrap 3. 

I also spent a fair bit of time brushing up on best practices for "px vs rem vs em". I found [this article](https://www.joshwcomeau.com/css/surprising-truth-about-pixels-and-accessibility/) to be most helpful.

This px vs rem vs em idea came from looking at the the [variable.scss](https://github.com/emory-libraries/blacklight-catalog/blob/main/app/assets/stylesheets/blacklight_catalog/_variables.scss) file for search.

**Comment by maxdmayhew** [comment]
![Screen Shot 2023-02-03 at 5.11.47 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/0181c3e7-eefa-45bf-b84f-877bfc6c834e)![Screen Shot 2023-02-03 at 5.17.33 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/afe22060-ba5f-45e0-91ce-bdc380fbaead)

submitting PR

**Comment by erussey** [comment]
@maxdmayhew : is this ready for QA?  If so, it's not quite matching the functionality of the wireframe for the right side of the header, which groups repositories and collections under a dropdown, suppresses unprocessed material, and adds a link to the help page and search (which is the homepage).

**Comment by maxdmayhew** [comment]
![Screen Shot 2023-02-08 at 1.24.40 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/55259599-2bb4-44b8-ac87-7c778c2f72cd)

@erussey Thank you for the reminder!
