### ISSUE TITLE
Adjust Test permissions.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#120]
Please create test permissions for Anna Elizabeth Sturgill that match the permissions for other archivists on the project per ticket #3.  Please remove all permissions for Erin Elizabeth Grimes.

**Comment by lisahamlett** [comment]
@erussey I have removed Erin Grimes from both instances.
In order to add permissions for Anna Sturgill, she will need to attempt to log in to the the system so Shibboleth can pull in her account information.

**Comment by erussey** [comment]
@lisahamlett : I just had her sign in, so her username should be available now.

**Comment by lisahamlett** [comment]
I have provided her with full access to all repos.
