### ISSUE TITLE
Implement banner in ASpace production beta release with link to a feedback form.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#121]
Please add the following text (with links) to the ASpace plug-in banner:

Welcome to the public beta of ArchivesSpace, the new Emory Libraries finding aids database. The site will officially launch at the end of July. Visit the [Help page](https://archives-test.libraries.emory.edu/help) for more information about ArchivesSpace. We encourage questions and comments via our [feedback form](https://emory.libwizard.com/f/ArchivesSpace_Feedback). 

EmoryFindingAids will remain available until August 2, 2023.

**Comment by abelemlih** [comment]
@erussey for reference, each time we need to update the banner, we will need to deploy a new version to the ArchivesSpace instance.

**Comment by abelemlih** [comment]
PR has been approved and merged. Please refer to the screenshot below:

![Screenshot 2023-05-11 at 4.01.14 PM.png](https://images.zenhubusercontent.com/6151f04e7e6954612001d8f9/762808fe-95cc-480c-9609-b18fb5bd906a)

**Comment by erussey** [comment]
@abelemlih : does that contain the links to the form and the help page?  Is it possible to have actionable links using that plug-in?

**Comment by abelemlih** [comment]
@erussey yes the banner contains links, and they are underlined in the UI as shown below:

![Screenshot 2023-05-12 at 12.37.36 PM.png](https://images.zenhubusercontent.com/6151f04e7e6954612001d8f9/e7b08dd9-3aab-45c1-92e2-f2b5a7de207c)

**Comment by erussey** [comment]
@abelemlih : Is this banner by default red? Or is it possible to change the color?

**Comment by tmill29** [comment]
@erussey will provide @abelemlih Hex code

**Comment by erussey** [comment]
@abelemlih : Please use #004990 (from the Emory pattern library) for the background of the banner above.

**Comment by abelemlih** [comment]
@erussey PR approved and merged. Please refer to the screenshot below:

![Screenshot 2023-05-17 at 4.09.27 PM.png](https://images.zenhubusercontent.com/6151f04e7e6954612001d8f9/ce21c616-cfde-471b-a916-8855cc1c5828)
