### ISSUE TITLE
Adjust repository badge display on repository pages in production

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#125]
The settings established in #70 for the repository pages aren't appearing in the production environment.

Test:
![Screen Shot 2023-04-07 at 8.48.49 AM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/45921e77-4fd2-4e82-a14f-8bacd64f636a)

Prod:
![Screen Shot 2023-04-07 at 8.49.05 AM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/1185459d-6afa-406a-af12-6f5318f00aa0)

**Comment by CB987** [comment]
So, I hate to just keep pushing stuff back on Lyrasis but this is again an issue that we had in test initially, and was something on their side that I think they had to "exclude" to let our overrides work. [This was the original basecamp conversation](https://3.basecamp.com/3410311/buckets/29543127/messages/5827135476), and this is what we currently have in the locale/en.yml:
`digital_object:
  _plural: 'Digital Materials'
agent:
  _singular: 'Names'
  _plural: 'Names'`
which mirrors the example Blake gave, and apparently works for test. I'm going to ask about this one in Basecamp also.

**Comment by CB987** [comment]
According to this response on basecamp from Friday:

We're excluding the Lyrasis generated plugin on dev, but are not currently doing that for prod. I'll exclude our plugin and restart things in the next 5-10 mins.

the badge labels should be fixed on prod. (They look right to me now,)
