### ISSUE TITLE
Curate/Aspace Integration: Missing administrative unit and holding repository

### ISSUE THREAD

**Issue by abelemlih** [emory-libraries/aspace#127]
Bug:

When a user on ArchivesSpace changes the name of a repository (e.g. accidentally adding a new line or space at the end of the name for instance), the strict mapping we enforce in the repository formatting service in Curate does not recognize the repository properly. This leads to empty values for administrative unit and holding repository for repositories that should have one.

Solution:

In Curate, within the `Aspace::FormattingService`, use the `repository_id` value in ArchivesSpace to identify a specific repository instead of its name.

**Comment by erussey** [comment]
@abelemlih : the mappings you provided look correct:
```
# holding repository

2 => "Pitts Theology Library",
3 => "Stuart A. Rose Manuscript, Archives, and Rare Book Library",
4 => "MacMillan Law Library",
5 => "Robert W. Woodruff Health Sciences Center. Library",
6 => "Oxford College Library (Oxford, Ga.)",
7 => "Stuart A. Rose Manuscript, Archives, and Rare Book Library"

# administrative unit

3 => "Emory University Archives",
7 => "Stuart A. Rose Manuscript, Archives, and Rare Book Library"
```
```
Pitts Special Collections and Archives: 2
Emory University Archives: 3
Emory Law Archives: 4
Woodruff Health Sciences Library Historical Collections: 5
Oxford College Archives: 6
Stuart A. Rose Manuscript, Archives, and Rare Book Library: 7
```

**Comment by abelemlih** [comment]
@erussey @eporter23 This ticket is ready for testing on Curate Test
