### ISSUE TITLE
Set up Google Analytics reports for production environment.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#128]
Set up the Google Analytics reports to 

- [ ] report on production data (currently configured for both test and prod)

- [ ] report similar information as Emory captures for other systems

- [ ]  grant access to Analytics data to Elizabeth Roke, Carrie Hintz, Brandon Wason, Ashley Stevens, Kerry Bowden, and Anna Sturgill

**Comment by erussey** [comment]
@erussey setting up a meeting with @eporter23 to discuss and review documentation: https://docs.google.com/document/d/17eOVrRaENta6LLQdg7EUSej52SSX4GzqQK_zE3VcbJ0/edit#heading=h.j5p4gw7nvkdi

**Comment by tmill29** [comment]
Elizabeth and Emily will meet on Monday to discuss
