### ISSUE TITLE
Amend Aeon plug-in configuration file

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#129]
Note: this ticket is a blocker on beta testing for the plug-in.  The following needs to be changed to be able to test the plug-in.  Each repository will need its own settings, though the information will be duplicated in most cases.

- [ ] We need to set the repo_code for each repository and then provide a mapping (:aeon_site_code) for each.  The below has the ASpace repo_code followed by the :aeon_site_code: The Aeon documentation notes that the repo_code must be written lower-case.  The Aeon site code needs to be all in caps. I am unsure if we need to change the short name for the repositories in ASpace to make them lowercase to fit the [requirement in the documentation](https://github.com/AtlasSystems/ArchivesSpace-Aeon-Fulfillment-Plugin/tree/prerelease#configuring-plugin-settings).

Rose MARBLEU
WHSCL HEALTHEU
Oxford OXFORDEU
EUA MARBLEU
Pitts THEOLOGYEU
Law LAWEU

- [ ] :aeon_web_url for all repositories needs to be set to point to our dualauth portal: https://emorytest.aeon.atlas-sys.com/Logon

- [ ] :return_link_label should be set to 'Return to ArchivesSpace' for all repositories

- [ ] :aeon_external_system_id should be set to 'ArchivesSpace' for all repositories

- [ ] :requests_permitted_for_containers_only should be set to true for all repositories

- [ ] :top_container_mode should be set to true for all repositories

- [ ] :request_in_new_ tab should be set to true for all repositories

- [ ] :hide_button_for_access_restriction_types should be set to 'Restricted' for all repositories

- [ ] Please confirm that the AppConfig for Test ASpace is set with the Test ASpace base URL per [ReturnLinkURL ](https://github.com/AtlasSystems/ArchivesSpace-Aeon-Fulfillment-Plugin/tree/prerelease#common-fields)

**Comment by erussey** [comment]
@abelemlih : I think this is ready to go.

**Comment by abelemlih** [comment]
@erussey  PR https://github.com/emory-libraries/aspace-deployment/pull/30 has been approved and merged. Once Aeon is configured correctly to save POST request data ([documentation](https://support.atlas-sys.com/hc/en-us/articles/360011821074#h_01FSYP1NVPGY3JGKTWPM9T3K7Q)), we can deploy a new version to Aspace Test and test the plugin. All the changes you requested above are merged and ready for release.
