### ISSUE TITLE
Create Operational Models (incident, support, content, development)

### ISSUE THREAD

**Issue by tmill29** [emory-libraries/aspace#130]
The scope of this ticket is operational support only for incidents and issues it does not include service requests, reports, development, enhancements, cost savings, or other types of operations. The steps below are to develop a shared understanding of the incident support model and documentation needed to provide immediate support for incidents as well as onboarding and continuity for LTDS staff to provide incident support for the product or application.

**Comment by erussey** [comment]
OLAs and documentation complete.
