### ISSUE TITLE
Adjust text on help page.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#144]
Please add the following text to the help page 

As a new final paragraph under "About ArchivesSpace"(along with the link to the accessibility page):
Emory Libraries is committed to the principles of universal design and strives to provide equitable services online and in our spaces. We assess and enhance the usability and accessibility of our digital interfaces on an ongoing basis, and use Section 508 of the Rehabilitation Act and current WCAG AA standards as benchmarks. For further information about Emory's accessibility standards and available services, please see [Emory Libraries' Accessibility Services](https://libraries.emory.edu/using-library/accessing-libraries/accessibility).

New text under "How to request materials"
Add sentence to end of paragraph: For additional help, please see the [How to Request Materials](https://archives-test.libraries.emory.edu/help-requesting) page.

**Comment by maxdmayhew** [comment]
changes made, submitting PR
https://github.com/emory-libraries/aspace_static_plugins/pull/54
![Screenshot 2023-05-12 at 12.14.10 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/413697a9-16c9-4834-b8a4-49a1e9356bbb)
