### ISSUE TITLE
Fix contrast issues on ASpace hompage.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#145]
Fix link contrast issues on the ASpace homepage by changing the opacity value of the grey box under the search boxes to #f3f4f8 to match Library Search.

![Screenshot 2023-05-10 at 9.15.10 AM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/3bd8455a-f2e3-48a3-b623-6f4e0ac4d70c)

**Comment by maxdmayhew** [comment]
![Screenshot 2023-05-12 at 11.10.09 AM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/df2f5285-cc7c-4a3c-be58-4b6a728c7ab4)

color updated

**Comment by maxdmayhew** [comment]
https://github.com/emory-libraries/aspace_static_plugins/pull/53
