### ISSUE TITLE
Adjust text on ASpace about page.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#147]
Please adjust the text on the ASpace About page: https://archives-test.libraries.emory.edu/about

Emory Libraries is committed to the principles of universal design and strives to provide equitable services online and in our spaces. We assess and enhance the usability and accessibility of our digital interfaces on an ongoing basis, and use Section 508 of the Rehabilitation Act and current WCAG AA standards as benchmarks. For further information about Emory's accessibility standards and available services, please see [Emory Libraries' Accessibility Services](https://libraries.emory.edu/using-library/accessing-libraries/accessibility).

**Comment by maxdmayhew** [comment]
submitting PR

![Screenshot 2023-05-12 at 10.39.30 AM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/07004c24-f798-4f8e-8dcf-ecf4783c030e)
