### ISSUE TITLE
Add text to the ASpace requesting help page.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#148]
Text, links, and images for this page are mocked up here: https://emory.sharepoint.com/:w:/r/sites/EmoryUniversityLibraries/Shared%20Documents/Project%20Management%20Office/EUL%20Projects/01%20Active%20Project/ArchivesSpace%20Phase%20II/02%20Planning%20and%20Execution/Workflow%20Implementation%20Team/Requesting%20help%20page%20language.docx?d=w0884ab59da74466ebaa2b68dc0c1be50&csf=1&web=1&e=EHRcut 

Note that the page includes some screenshot images that need to be included with the text.  Headers are in bold.

**Comment by maxdmayhew** [comment]
@erussey do you have the text for this ticket?

**Comment by erussey** [comment]
@maxdmayhew : Just added the page text to the ticket.  Let me know if you have questions!

**Comment by maxdmayhew** [comment]
updated the estimate since this page is a bit longer than the others and has images and several links.

**Comment by maxdmayhew** [comment]
PR submitted

https://github.com/emory-libraries/aspace_static_plugins/pull/56

**Comment by erussey** [comment]
@maxdmayhew : The screenshot of the buttons has the hover text.  Can we also get the screenshots of the warning messages a little cleaner (I'm seeing part of the header in the first one)?  All the screenshots are also way too big.

**Comment by maxdmayhew** [comment]
![image.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/5429c71b-6c83-45b1-81f0-9fb39a190a1f)

image sizes updated and cleaned up, submitting PR
