### ISSUE TITLE
Customize the homepage for ArchivesSpace PUI

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#15]
Implement the requirements for the ASpace discovery layer homepage documented in ASpace ticket #50.

Wireframe of requested customization in comments.

- Footer requirements documented in [ticket #11](https://app.zenhub.com/workspaces/archivesspace-63122393d517dc001c3ceb07/issues/gh/emory-libraries/aspace/11)

- Header requirements documented in [ticket #12](https://app.zenhub.com/workspaces/archivesspace-63122393d517dc001c3ceb07/issues/gh/emory-libraries/aspace/12)

- Search bar can be used as is from the out-of-the-box application (with amended colors/fonts)

- Please follow styling/fonts/colors from [ticket #18](https://app.zenhub.com/workspaces/archivesspace-63122393d517dc001c3ceb07/issues/gh/emory-libraries/aspace/18)

**Comment by erussey** [comment]
Wireframe:[https://app.zenhub.com/files/531984195/3b9e29f5-558c-4de5-9ca0-a8fa0667ec97/download](https://app.zenhub.com/files/531984195/3b9e29f5-558c-4de5-9ca0-a8fa0667ec97/download)
Notes:
1.  Dropdown menu

2.  Click on logo returns to ASpace homepage

3.  Please be sure this rescales for mobile devices (as is done for Emory Digital Collections).  Note that I noticed a bug in LibrarySearch (it's not resizing on mobile), so don't follow that pattern.

4.  Link to https://libraries.emory.edu/materials/archives-and-special-collections

5.  Link to ASpace help page

6.  Link to https://emory-dev.lyrasistechnology.org/repositories

7. Link to https://libraries.emory.edu/contact/ask-librarian

**Also note that I realize that sizing is off in the wireframe due to my non-existent web designer skillset.  Please follow similar sizing for search boxes/banner images/footers/etc. based on Emory Digital Collections and Library Search.

**Comment by erussey** [comment]
Banner image (let me know if a higher resolution is needed):![0061101-21KH-F101_ZOOM.jpg](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/c9f69aec-0c53-4124-bc71-ac9d80e31da3)

**Comment by maxdmayhew** [comment]
Currently the site is setup to be full width out of the box. The wireframe does not specify what exactly should be done for larger monitor sizes. Here are two options. We could also use a mix of them as well if we want.

![Screen Shot 2023-02-09 at 4.33.32 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/29c5d705-7a22-4d59-b0d9-5733dcd7a9d7)

![Screen Shot 2023-02-09 at 4.29.13 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/a00388e4-0b49-4337-afaa-d79a23a6ff7a)

**Comment by erussey** [comment]
@maxdmayhew : What does Library Search do?  I prefer the full width version, myself, but mostly I want to match what has been done in Library Search.  Can we put in the text (the grey box) from the wireframe so we can see what this looks like before making a decision?

**Comment by erussey** [comment]
@maxdmayhew : Could we adjust the spacing of the text in the header?  In the second view you provide above it's basically a wall of text across the top.  Library Search and Emory Digital collections seem to have a more evenly matched spacing (with a whitespace gap between the left and right), even in a small window. For the question above, let's use the second for now without the full width since it matches our other discovery sites, but we might need to change our minds on that one depending on how testing goes in the full site (I don't want text wrapping in weird ways).
