### ISSUE TITLE
Implement the backup data process 

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#152]
See issue #95.  I assume that the setup and Emory server is set up already, but we need to put in the request to Lyrasis to implement the regular backups.

**Comment by kbowaterskelly** [comment]
The ArchivesSpace backup Lambda function has been scheduled to run on the first of the month and successfully pulled the sql db to our s3 bucket.

To do:
Document and hotlink this process in the wiki

Next ticket:
Validate our backup / restoration on a test or arch instance

**Comment by erussey** [comment]
Ticket #154 created for data validation.  @kbowaterskelly will be creating the sysadmin-related documentation in the ASpace confluence page: https://wiki.emory.edu/display/EAS/Backup+copies . This documentation will include details about setup, frequency, and location of the data.
