### ISSUE TITLE
Button order of Aeon requesting boxes changed with the latest update.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#153]
In the latest update of the Aeon plug-in, the warning messages are no longer showing last in the order of the buttons.  ![Screenshot 2023-05-23 at 2.07.17 PM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/3aea92e9-68e7-4eb6-8aa4-4cbaedb9746a)

**Comment by maxdmayhew** [comment]
@erussey can we set up a time to meet to go over this ticket? Or maybe review after todays meeting?

**Comment by erussey** [comment]
Absolutely.  Here's an example of what I'm seeing:
Button looks ok: https://archives.libraries.emory.edu/repositories/7/resources/2231
Button shifts: https://archives.libraries.emory.edu/repositories/7/archival_objects/54675

**Comment by maxdmayhew** [comment]
PR submitted yesterday 

https://github.com/emory-libraries/aspace_static_plugins/pull/60

**Comment by erussey** [comment]
Looks good.  Moving to done.
