### ISSUE TITLE
Validate the ASpace backup copy and determine process for backup restoration to test/QA

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#154]
Validate the backup copy of ASpace.  This includes:

- determining a process for restoring backups to the test instance (in consultation with Lyrasis) or a locally installed instance upon request

- installing the backup copy in test or a local instance in consultation with @erussey to ensure that all the data has been captured in the backup

- documenting decisions on the ASpace confluence page

**Comment by kbowaterskelly** [comment]
I pulled down a copy of the backup on the 2nd and it was restored to the test environment on the 3rd.  It should now be fully indexed and ready for validation by @erussey. 

We take backups on a monthly basis on the first/second of the month. The process for restoring backups on demand at this time consists of retrieving a copy of the .sql file from AWS S3 storage and transmitting it to Lyrasis via their secure file transfer application @ files.lyrasis.org (they have to provide you an account for that) and requesting they restore it to the environment we select. 

A restore to a locally hosted application would need to be explored further if desired. I do not have a good grasp of how much effort it is to locally host this application at this time. I'd suggest considering forking other tickets off as needed.

**Comment by erussey** [comment]
This looks good.  I can see the backup copy in test and records seem to all be there.  I will add the documentation listed above to the Confluence page.
