### ISSUE TITLE
Implement redirect for EmoryFindingAids site.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#155]
Create a redirect from all links on the http://findingaids.library.emory.edu domain to https://archives.libraries.emory.edu

Please notify @erussey upon completion so that a heads up can be sent to stakeholders.

**Comment by tmill29** [comment]
Work on this ticket can begin on July 26th or after, once Elizabeth returns from vacation.

**Comment by kbowaterskelly** [comment]
This has been accomplished with RedirectMatch and a bit of regex. All requests to findingaids.library.emory.edu and any sub directories should be redirected to archives.libraries.emory.edu.

**Comment by erussey** [comment]
Looks good.
