### ISSUE TITLE
LCNAF plug-in not appearing on the staff-side application.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#156]
This bug is related to #83.  We previously were able to see this plug-in in the staff UI, but no longer can.  The master plug-in is located here: https://github.com/archivesspace-plugins/lcnaf

Users should be able to see this:
![169982fd-2bbe-43b6-98f5-52f28dafa6f1.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/49874197-6c06-480d-b169-83c201b06e74)

![54f1d4ca-20b8-4211-94e7-cf834017f44c.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/2b8f751d-f4e9-4c60-8dec-46ada1421c60)

**Comment by bwatson78** [comment]
Ongoing discussion with Blake from Lyrasis about bug resolution: https://3.basecamp.com/3410311/buckets/29543127/messages/6236625145

**Comment by erussey** [comment]
@bwatson78 : after restart, I see it in prod:

![Screenshot 2023-06-21 at 11.12.19 AM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/5a010457-8125-44bb-ab23-f2245fdb1932)

Do we need to figure out what change we need to make on our end so the plug-ins match?  I appreciate him making that change, but we will run into this again the next time we send our plug-in files to them for an update.

**Comment by bwatson78** [comment]
Per Blake from the basecamp conversation above:
```
OK, that did it. As it was restarting I noticed what the problem was. There was a name collision between your lcnaf plugin and the "real" plugin, so I just changed it up here and that did the trick! Sorry about that, it wasn't obvious until I saw it happen.
```

I take this to mean that their deployment code on their side was throwing errors because they were named the same and their code’s expectation is to deploy the base github repo only. He has assured us that this shouldn't happen in the future because of the changes he has made on their side.

**Comment by erussey** [comment]
We have tested this and the plug-in is working on both prod and test now.
