### ISSUE TITLE
Create banner on Emory Library websites

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#157]
Please create a banner on the following repository pages to announce the new ArchivesSpace discovery interface.  The banner should remain up until September 15.  Please make it a color that is non-alarming (i.e. not red).  It should go on the following:

https://libraries.emory.edu/rose (top level page and subpages)
https://libraries.emory.edu/health/using-library/historical-collections (this page only)
https://oxford.library.emory.edu/special-collections (this page and children of this page only)

Banner text:
Emory University has a new discovery interface for archival and manuscript collections. To try it out, visit https://archives.libraries.emory.edu. We welcome your [feedback](https://emory.libwizard.com/f/ArchivesSpace_Feedback)!

**Comment by erussey** [comment]
I believe that Law and Theology templates are not owned by LTDS?

**Comment by maxdmayhew** [comment]
notifications show up for the entire site, not specific pages.

**Comment by CB987** [comment]
[Colin Bragg shared instructions for creating banners on individual pages.](https://emory.sharepoint.com/:w:/r/sites/EmoryUniversityLibraries/_layouts/15/Doc.aspx?sourcedoc=%7BEBF1206B-74C7-4B25-9802-80F9F873A924%7D&file=02b%20Adding%20a%20Notice%20to%20a%20Page.docx&action=default&mobileredirect=true) 
Unfortunately, this is one page at a time, so it may take a bit longer for the multiple pages under /rose/. I'm going to get started but may have to move the estimate up.

**Comment by CB987** [comment]
Notice: ArchivesSpace (keep until Sept 15, 23)
<p>
    <strong>Notice: </strong>Emory University has a new discovery interface for archival and manuscript collections. To try it out, visit <a href="https://archives.libraries.emory.ed" target="_blank">https://archives.libraries.emory.edu</a>. We welcome your <a href="https://emory.libwizard.com/f/ArchivesSpace_Feedback" target="_blank">feedback</a>!
</p>

**Comment by CB987** [comment]
/rose/ ✅
/health/using-library/historical-collections ✅
oxford.../special-collections/ ✅ there are no child pages of special-collections
these are done. there are 134 subpages of rose, however, so i'm going to take a little time to see if there's a more efficient way besides just adding to individual pages.

**Comment by lovinscari** [comment]
As discussed during standup today, @CB987 has updated the banner manually on the Rose, WHSL, and Oxford Library landing pages. She will focus on also adding to https://libraries.emory.edu/rose/using-rose-library/preparing-research-visit/digital-archives-access, https://libraries.emory.edu/rose/using-rose-library/preparing-research-visit/requesting-materials-rose-library, https://libraries.emory.edu/rose/using-rose-library/preparing-research-visit/making-or-changing-appointment and the main libraries landing page. @maxdmayhew will create a new ticket on the web zenhub board with an enhancement to automate the process of adding banners to pages.

**Comment by CB987** [comment]
https://libraries.emory.edu/rose/using-rose-library/preparing-research-visit/digital-archives-access, ✅
https://libraries.emory.edu/rose/using-rose-library/preparing-research-visit/requesting-materials-rose-library, ✅
https://libraries.emory.edu/rose/using-rose-library/preparing-research-visit/making-or-changing-appointment ✅
main libraries landing page ✅
I went ahead and added it to /rose/using-rose-library/ and /rose/using-rose-library/preparing-research-visit/ as well since those are direct parent pages of the ones you specified.

**Comment by maxdmayhew** [comment]
```
/rose
/rose/*
/health/using-library/historical-collections
/special-collections
/archives/collections
/archives/*
```
these are the pages I have included. Does this look appropriate?

PS: can we keep this ticket around until the new custom block is up so we don't forget to remove the old notifications that are up currently?
