### ISSUE TITLE
Change banner text in ArchivesSpace.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#159]
Please revise the banner text to:

Welcome to ArchivesSpace, the new Emory Libraries discovery system for archives.  Visit the [Help page](https://archives.libraries.emory.edu/help) for more information about using ArchivesSpace.  We encourage questions and comments via our [feedback form](https://emory.libwizard.com/f/ArchivesSpace_Feedback).

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/aspace_static_plugins/pull/62
