### ISSUE TITLE
Configure browse menu

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#16]
Implement the requirements for the ASpace discovery layer homepage documented in ASpace ticket #50.

- [ ] Navigation bar: display options, terminology

- [ ] Add link to [help page
](https://app.zenhub.com/workspaces/archivesspace-63122393d517dc001c3ceb07/issues/emory-libraries/aspace/64)
Please work with Lyrasis to implement these changes.

**Comment by rotated8** [comment]
The requirements here are unclear. We aren't sure how different they are from what currently exists.

**Comment by erussey** [comment]
Redundant ticket.  This issue is covered in #50.
