### ISSUE TITLE
Change Alma proxy text(?) to point to ArchivesSpace

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#161]
Please change the referral page from LibrarySearch/Alma to point to ArchivesSpace.  The link will be updated to ArchivesSpace per #27

Text should be: 
This item is requestable through ArchivesSpace.

Title: xxx
RecordID: xxx

The item you selected is an archival collection, which can include many boxes or items.  Please search for the collection in ArchivesSpace [hyperlink ArchivesSpace here with the pid link from the Alma record] to review the finding aid and select the individual boxes or items you would like to use. Click on the Aeon Request button in ArchivesSpace to log into Emory University's Special Collections Request System to request the materials and make an appointment. 

Example:
https://libapiproxyprod1.library.emory.edu/cgi-bin/booking_findingaids?doc_id=990031606370302486&user_id=0

![Screenshot 2023-06-23 at 12.45.34 PM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/eb7b067d-5d51-4dcc-92a4-be2a3bac085e)

**Comment by AGCooper** [comment]
I updated /sirsi/webserver/docs/booking_finding_aids.html on libapiproxyprod1.library.emory.edu with the requested text.

**Comment by erussey** [comment]
Tested and looks great!
