### ISSUE TITLE
Create issue reporting form for ArchivesSpace/Aeon

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#162]
Create a standardized form for ticket requests for ArchivesSpace/Aeon.  First draft is here: https://emory.libwizard.com/f/archivesissuereporting

**Comment by erussey** [comment]
@lisahamlett : looks pretty good!  A couple of changes:

1.  Delete the question beginning "Were there any changes made before the issue arose...."
2.  Add a dropdown question: "What system are you experiencing problems with?" [dropdown: Aeon, ArchivesSpace]
3.  Add a dropdown question following #2 above: "For ArchivesSpace issues, is your issue related to the staff side application or the public discovery interface?" [dropdown: staff application, public discovery interface]
4.  Add a dropdown question following #3 above: "For Aeon issues, what is the nature of your problem or request?" [dropdown: client installation or printing, configuration or webpage change, other]

**Comment by erussey** [comment]
@lisahamlett : And one other that will come out of the meeting on Thursday.  Once we define the priority levels, I'd like to put those in here as well and ask them to select the issue urgency.  I'll comment on the ticket once we have those defined.  Alternatively, if you share permissions to the form with me in LibWizard, I'm happy to make the changes myself.

**Comment by lisahamlett** [comment]
@erussey I have given you edit permissions.

**Comment by erussey** [comment]
I have gotten the form mostly to where it needs to be, but will need to be revised following the OLA discussion on Thursday, August 3 defining the various tiers of support.

**Comment by erussey** [comment]
Form revised.

**Comment by erussey** [comment]
Form revised.

**Comment by erussey** [comment]
Form revised.
