### ISSUE TITLE
Delete EFA SQL databases and applications

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#164]
- [x] Confirm with OIT the deletion of the SQL databases (September 14)- Collin Brittle

- [x] Delete the EFA applications off the server (September 14)
- [x] Delete the old data from SVN (September 14)

The test application, test SVN data, and test SQL database can be deleted as soon as is feasible.  The production application, production SVN data, and production SQL database cannot be deleted until September 14 to give time for stakeholder notification.

**The following applications will need to remain per discussion in #40: Fedora, RabbitMQ, eXist, SOLR, (possibly SVN/SVNmount) needs to remain in place as-is. Need to investigate if there are changes that need to be made to celery.

**Comment by erussey** [comment]
I have scheduled two meetings to manage this issue post-launch on 9/6 @1pm and 9/14@3pm.

**Comment by erussey** [comment]
Per discussion on 8/18, the tasks in this ticket may be done in any order.  The goal is to complete all of these tasks by 9/14 to stay in alignment with the OIT server project.  Deletion of the EFA applications off the server only covers the EFA application/test application.  It does not include any dependencies as noted in the ticket.

**Comment by erussey** [comment]
Confirming for the ticket that we are good to go with deletion.  I have not heard any concerns from stakeholders related to this action.

**Comment by kbowaterskelly** [comment]
DBs were dropped in ticket INC04123255
Application test and prod deleted
SVN data scrubbed

Ready for review, noting here I need to either reimplement a redirect or a DNS canonical name change for findingaids.library
I am assuming we should drop the SVN repo "findingaids" but I didn't see that on the list and I didn't pull a copy down yet so leaving it for now

**Comment by kbowaterskelly** [comment]
Here is a list of the remaining SVN repos

afampamph              ecp                 hdot                metacombine          portlet_NewBooks        sspmigration
african_origins        edc_data_freeway    hdot-php            metalib_portlet      portlet_RSSPrimo        steve
aptdump                edc_web_search      help                methodist            Primo                   steve2
atlmaps                ejournals_finder    httpstatus          mike                 python-eulcore          SymplecticConnector
belfast                eliotx              icdb                mobile_applications  rd_registrar_scripts    tracmodifications
binmarc2marcxml        emorylib-mediawiki  iGoogle_Primo       molvis               readux                  webns
civilwar               etd                 iGoogle_Primo_svn   mystaffweb           retention               wgf
core_services          EULwebs             iln                 namespace-uri-docs   rssportlet              xmldbOAI
dawson                 ewwrp               isrs                newbooks_portlet     rushdie-tools           xml-utilities
db_locator             ewwrp-php           javascript_eulcore  ocm_finder           schanges                xquery-modules
digital_innovations    ez_mvc              lcstats             openemory            schemas                 yeats
digital_masters        fedora              lincoln             openportal           scriptaculous           yjallen
digitization_workflow  fez                 local-fedora        oxfordexperience     SearchPro               zendPing
disc_trac              findingaids         local-pdfbox        pdcheck              slavevoyages            zGizmo
django-eulcore         formfaces           lsdi                persis               smallpox
drm                    frenchrevolution    mapportlet          podcast_template     small_projects
drupalsites            gadget              Marc8CharSet        portlet_Itunes       southcomb
dummy                  gl_hours            merton              portlet_LDAPlogin    southernspacesmetaform
dwrangler              greatwar            metaarchive         portlet_Metalib      spatialvision

**Comment by erussey** [comment]
Leaving the findingaids SVN repository in place is correct.  We didn't want to touch that for fear it would take the Keep infrastructure down.  However, we do need a plan soon to get the redirects back.  I don't think I realized it would take that down when we took the application down.  Google is still showing old search results to EFA, so we do need those redirects to avoid patron confusion.

**Comment by libdgg** [comment]
Kaeln put a bandaid fix on it until the correct dns record is added. should be fine for now.

**Comment by kbowaterskelly** [comment]
Not able to do this with DNS at this time because ArchivesSpace is vendor-hosted. We will maintain a redirect on our side going forward. I don't believe there are any remaining issues, we should be ready to close this.
