### ISSUE TITLE
Amend help documentation for Aeon requesting

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#166]
We would information to be added to the suite of help pages with a step-by-step procedure for requesting materials from Aeon to help users navigate the site.  If possible, I'd like to mimic the styling of Columbia's help page where the screenshot displays to the right of the explanatory text: https://library.columbia.edu/libraries/avery/da/aeon.html

- Please add the following text to the how to request materials paragraph (https://archives.libraries.emory.edu/help#request-aspace): ...For additional help, please see the How to Request Materials page, which includes a step-by-step walkthrough of how to request materials.

Amend https://archives.libraries.emory.edu/help-requesting by:

- Adding a navigation menu
- Replace "Requesting Materials" with the heading "Making a Reading Room Request from ArchivesSpace"
- Replace all the text underneath the old Requesting Materials header with the information in the attached document.[Making a Reading Room or Copy Request from ArchivesSpace .docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmZ5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c20e91d774ecdf49bbf9d2c51087904bffb26219/Making%20a%20Reading%20Room%20or%20Copy%20Request%20from%20ArchivesSpace%20.docx)

**Comment by erussey** [comment]
Documentation changes requested:[https://app.zenhub.com/files/531984195/3c2b5b0a-8e54-4ecf-8466-05d3727a5150/download](https://app.zenhub.com/files/531984195/3c2b5b0a-8e54-4ecf-8466-05d3727a5150/download)

**Comment by CB987** [comment]
@erussey just to clarify, would "adding a navigation menu" mean like a table of contents that incorporated links to sections?

**Comment by erussey** [comment]
@CB987 :  Yes, that's what I'm envisioning.  Like the help menu here: https://archives.libraries.emory.edu/help

**Comment by CB987** [comment]
@erussey would you mind giving your input on the section names for the nav menu please? Below are my working names but I don't know if that's the most helpful from a user perspective. 
<img width="734" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTl0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d88efe7299cfbea980f149b1d8bc85010db0ae7/Screenshot%202024-06-17%20at%203.13.19%E2%80%AFPM.png" alt="Screenshot 2024-06-17 at 3.13.19 PM.png" />

**Comment by erussey** [comment]
@CB987 May I suggest the following? :

- Searching for materials
- Making a request from ArchivesSpace
- Additional help

Could we put the unrequestable items section under the additional help as a subhead?  It probably makes more sense there.

**Comment by CB987** [comment]
sounds good! thanks

**Comment by CB987** [comment]
PR#63 for the first part, not including the Columbia styling.

**Comment by CB987** [comment]
@erussey would you give this a once-over please and make sure all is as expected, *pre-*columbia styling? 
<img width="379" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEZ1QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca721992b136f7b8556d71b6d9938f08c5b887b6/screencapture-localhost-3001-help-requesting-2024-06-17-16_01_56.png" alt="screencapture-localhost-3001-help-requesting-2024-06-17-16_01_56.png" />

**Comment by erussey** [comment]
@CB987 : The menu and headers look good as does the arrangement of the page.  But I assumed that the images in the attached document would appear in the page.  The screenshots are key even if we can't get the Columbia arrangement of things.

**Comment by CB987** [comment]
Ah! Ok, glad I asked ;)

**Comment by CB987** [comment]
[screencapture-localhost-3001-help-requesting-2024-06-26-12_29_48.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBektVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b98a7b2907a9144dd745a53830d9f5c736788186/screencapture-localhost-3001-help-requesting-2024-06-26-12_29_48.pdf)

@erussey I think we are getting closer. Let me know what you think. If it would be helpful to meet to go over it, I am happy to do that. 
Thanks!

**Comment by CB987** [comment]
https://web.archive.org/web/20220628194038/https://library.columbia.edu/libraries/avery/da/aeon.html

**Comment by erussey** [comment]
@CB987 : I have the go-ahead from stakeholders to proceed with the screenshots as is.  We'd prefer not to do extra work if we don't have to and will see if users notice.  One grammar change under the header "Making a Photoduplication Request": If you would like to submit a photoduplication request for archival resources please email us.

**Comment by abelemlih** [comment]
PR https://github.com/emory-libraries/aspace_static_plugins/pull/63 approved and merged
