### ISSUE TITLE
Retire EFA KB article and Configuration Item in ServiceNow

### ISSUE THREAD

**Issue by libdgg** [emory-libraries/aspace#168]
- [x] Retire the KB article [KB05077 ](https://emory.service-now.com/nav_to.do?uri=%2Fkb_knowledge.do%3Fsys_id%3D4273ec9113e7ce00bcfe7d322244b0cb%26sysparm_view%3D%26sysparm_record_target%3Dkb_knowledge%26sysparm_record_row%3D1%26sysparm_record_list%3Du_knowledge_champion%253Djavascript%253Ags.getUserID%2528%2529%255EORauthor%253Djavascript%253Ags.getUserID%2528%2529%255E123TEXTQUERY321%253Dfinding%255EORDERBYzztextsearchyy%26sysparm_record_rows%3D6)in ServiceNow: "[How to Batch Publish EmoryFindingAids EAD XML documents](https://emory.service-now.com/kb_view.do?sysparm_article=KB05077)"
- [x] Retire the Configuration Item in ServiceNow: [FindingAids](https://emory.service-now.com/nav_to.do?uri=%2Fcmdb_ci_appl.do%3Fsys_id%3D8483614b74cbf500979faec14a918271%26sysparm_record_target%3Dcmdb_ci_appl%26sysparm_record_row%3D1%26sysparm_record_rows%3D1%26sysparm_record_list%3Dsys_class_name%253Dcmdb_ci_appl%255EnameCONTAINSfinding%255EORDERBYname)

**Comment by libdgg** [comment]
@rotated8 @erussey @AGCooper I have retired the Finding Aids KB article and Configuration Item in ServcieNow.

**Comment by erussey** [comment]
Great!  I think this ticket can be closed.
