### ISSUE TITLE
Configure search menu

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#17]
Implement the requirements for the ASpace discovery layer homepage documented in ASpace ticket #50.

- [ ] Search message and scoping options: the greyed out text in the search boxes and the drop down options

Please work with Lyrasis to implement these changes.

**Comment by rotated8** [comment]
We cannot estimate this ticket without more information that appears to be coming from #50.

**Comment by erussey** [comment]
After review of #50, this ticket is not needed.  Default options are fine.
