### ISSUE TITLE
Batch update digital objects from the Keep for the Rose and EUA repositories

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#170]
Due to the migration, all digital objects from the Keep are currently unpublished.  Tasks for this ticket are:

- Publish all digital objects in the Rose and EUA repositories with a file version that has a file URI in this format: http://pid.emory.edu/ark:/25593/### .  The publish box needs to be checked on both the digital object level and the file version level.
- Add a caption of "Digital file available only in the Rose Library reading room."
- Once the update is done, create a report of all the digital objects from the Rose and EUA repositories.  It should contain: the ASpace identifier for the digital object (not the digital object id, which is a hash), the repository, the collection name, the collection number, publication status of the digital object, associated file version file URI(s), title of the digital object, title of the parent archival object

An example file in ASpace test with requested changes is available here: https://archives-test.libraries.emory.edu/staff/digital_objects/375/edit#tree::digital_object_375  A report for this object would show:
ASpace identifier: https://archives-test.libraries.emory.edu/staff/digital_objects/375
Repository: Rose
Collection name: Alice Walker papers
Collection id: Manuscript Collection No. 1061
publication status: true
File version URI: http://pid.emory.edu/ark:/25593/b7x31
Title: Alice Walker Talking with Professor Staughton Lynd, Young Unitarians, October 1962 [pid: b7x31]
Title of archival object: Alice Walker Talking with Professor Staughton Lynd, Young Unitarians, October 1962

Please run this in test first, so we can check results before running this on production data.

**Comment by erussey** [comment]
Test object: https://archives-test.libraries.emory.edu/staff/digital_objects/17901#tree::digital_object_17901 

Looks good and I'm ok running the full update of all objects in test.  Ayoub is working on trying to generate a report that will include collection information, which would be useful in the Rose Library to validate results and identify objects that need manual intervention.

**Comment by abelemlih** [comment]
@erussey I created a change [request](https://emory.service-now.com/nav_to.do?uri=task.do?sys_id=c0f733561b56b950f24db887cc4bcb05) for running the ArchivesSpace script in production. I set the planned start date for the change to 2023-11-09 02:00 PM to ensure Doug and Collin have enough time to approve. Let me know if you have any questions.

**Comment by abelemlih** [comment]
All digital objects were updated in production. I sent the generated report to @erussey.
