### ISSUE TITLE
Remove banners from library websites related to ASpace launch.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#173]
Please remove the banners created in #157 on library websites.

**Comment by lovinscari** [comment]
@cwbragg - will take a look at this ticket to see if this is a content request or developer request.

**Comment by cwbragg** [comment]
This mostly looks like a content request. I will go through ticket #157, gather the links, and share them with the relevant czars for removal.

**Comment by cwbragg** [comment]
I removed the notice banner from these individual pages:

https://libraries.emory.edu/health/using-library/historical-collections 
https://oxford.library.emory.edu/special-collections
https://libraries.emory.edu/rose/using-rose-library/preparing-research-visit
https://libraries.emory.edu/rose/using-rose-library
https://libraries.emory.edu/rose/using-rose-library/preparing-research-visit/digital-archives-access x https://libraries.emory.edu/rose/using-rose-library/preparing-research-visit/requesting-materials-rose-library  https://libraries.emory.edu/rose/using-rose-library/preparing-research-visit/making-or-changing-appointment

**Comment by erussey** [comment]
Thanks @cwbragg .  I've reviewed the pages above and marking this as done.
