### ISSUE TITLE
Batch change restrictions language in Rose Library and EUA collections

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#175]
Change text within the Restrictions Governing Access field in the Rose and EUA repositories from

"Collection stored off-site.  Researchers must contact the Rose Library in advance to access this collection."

to

"Collection stored off-site; materials must be requested two business days in advance of appointment."

<img width="1340" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzE4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac610a594e5f8b49f5466e1ac4427b3872d35694/Screenshot%202024-02-21%20at%204.53.42%E2%80%AFPM.png" alt="Screenshot 2024-02-21 at 4.53.42 PM.png" /> https://archives.libraries.emory.edu/staff/resources/2431/edit#tree::resource_2431

Note that there may be other text or other subnotes within the Restrictions Governing access field as in https://archives.libraries.emory.edu/staff/resources/3391/edit#tree::resource_3391.  Only the text string above should be replaced.

**Comment by erussey** [comment]
@erussey Will ask Rose whether a policy page can be set up for these type of change in the future rather than a data change.

**Comment by abelemlih** [comment]
@erussey a quick question to clarify requirements: would changing all object of record type "Resource" and with a note of type "Conditions Governing Access"  and label "Restrictions on Access" fulfill all the requirements of this ticket? Let me know if there are other record types that should be updated.

As for the update, I plan on running a bulk update via the API on Test, to verify changes, then production once changes are approved.

**Comment by erussey** [comment]
@abelemlih Yes, just checked with stakeholders and that note is only attached to resource objects.  I might be careful with that label though...it's generally true that the note type Conditions Governing Access has a label of Restrictions on Access, but they are starting to drop that label (which is a remnant of the migration).

**Comment by abelemlih** [comment]
@erussey is it correct then to update all objects of record type "Resource" and with a note of type "Conditions Governing Access", regardless of label? I just want to clarify which conditions to set for the API update.

**Comment by abelemlih** [comment]
I worked on two scripts, once to compile all relevant resources that we need to update, and one to run the actual update. Below are two resources I updated on Test to match the new note text:

- https://archives-test.libraries.emory.edu/staff/resources/2229
- https://archives-test.libraries.emory.edu/staff/resources/2418

I reached out to Elizabeth for verification and approval. As for next steps, I will update the Test instance in bulk, and once approved, we can run a report of all resources that are relevant in production before we run a bulk update.

**Comment by erussey** [comment]
@abelemlih We're not catching everything in the current script to find the relevant resources.  There are examples (see https://archives-test.libraries.emory.edu/staff/resources/3206#tree::resource_3206) that have additional text in the note.  The same text needs to be changed in these with the other part of the note unchanged.  Is that possible?  When I just did a kw search for the number of resources with the word off-site in the test UI, I got 342 results.

**Comment by abelemlih** [comment]
I sent Elizabeth an updated report with all resources whose access restriction note includes text "Collection stored off-site. Researchers must contact the Rose Library in advance to access this collection." instead of matching it exactly. I will move forward with a bulk update once the report is approved

**Comment by erussey** [comment]
@abelemlih : Yes, that is a more accurate report.  You can go ahead and try the bulk update in test.  Note that the change should only replace the text it matches on.  The rest of the note should stay as is.

**Comment by abelemlih** [comment]
I updated all resources on Test. Once verified and approved by @erussey, I will move forward with compiling a list of all relevant resources in production and update them.

**Comment by erussey** [comment]
Checking with stakeholders to be sure that the data looks ok.  I should be able to give the go-ahead Wednesday or Thursday.

**Comment by erussey** [comment]
@abelemlih : I've gotten the go-ahead to proceed with the changes above in production.  I would appreciate a report of the resource objects that were changed.

**Comment by abelemlih** [comment]
@erussey sounds good, I will run a report of all items that need to be updated tomorrow, verify it with you, then proceed with the actual update. I plan on working on these tasks tomorrow morning.

**Comment by abelemlih** [comment]
@erussey I updated all relevant resources in production and sent you a report of all resources updated on Slack. This ticket is ready to close.
