### ISSUE TITLE
Upgrade ASpace to 3.5.1

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#177]
Patch release that addresses issues in 3.5.0

https://github.com/archivesspace/archivesspace/releases

**Comment by erussey** [comment]
@alexBLR : per Ayoub's recommendation, we should apply 3.5.1 to test rather than deploying the 3.5.0 release to prod.  Please keep the configuration and code changes that are currently in test, which reflect changes that were made to accommodate 3.5.0.  Procedures for deployment are here: https://github.com/emory-libraries/aspace-deployment

**Comment by alexBLR** [comment]
Archive Space Test has been deployed and upgraded to 3.5.1. Please, make sure to test it so I can make changes if there are any errors: https://archives-test.libraries.emory.edu/

**Comment by erussey** [comment]
We have begun testing.  I have noticed some indexing issues with the Rose repository, so I sent a ticket to Lyrasis to request reindexing for the PUI.  We will be able to resume testing when that is complete.

**Comment by lovinscari** [comment]
@erussey - can you please note any of the indexing issues you are seeing in the comments?

**Comment by erussey** [comment]
@lovinscari @alexBLR : I put in a request to Lyrasis to do a reindex on test, which is running right now.  The issue was with the Rose Library repository...items in the container list were displaying a 404 message rather than displaying the archival object.  Here's the example I reported to Lyrasis:  https://archives-test.libraries.emory.edu/repositories/7/resources/2609. Once I get a message indexing is complete (should be today), I'll recheck and continue testing.

**Comment by erussey** [comment]
@alexBLR : Testing of 3.5.1 complete.  All tests passed.  We are ready to submit a change request and deploy to prod.  We will need to coordinate with the libraries and Lyrasis to deploy.  I will check in with them tomorrow to find a suitable date.  Is next week too soon for the change request @rotated8 ?
