### ISSUE TITLE
Configure fonts, colors, and styling

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#18]
Please update the text colors, link colors, and background color within ArchivesSpace.  These profiles should match current standards at Emory University and those that were used for LibrarySearch.

You will need to check with Lyrasis to see if these changes apply only to the homepage or if they can apply throughout the site.

**Comment by CB987** [comment]
https://archivesspace.github.io/tech-docs/customization/theming.html
"You can customize CSS through the plugin system too. If you don’t want to create a whole new plugin, the easiest way is to modify the ‘local’ plugin that ships with ArchivesSpace (it’s intended for these kind of site-specific changes). As long as you’ve still got ‘local’ listed in your AppConfig[:plugins] list, your changes will get picked up."

**Comment by maxdmayhew** [comment]
Working on clearing up a tooling question with Collin. Overall should be fairly straightforward once that is resolved. Below is just an example of some very basic styling applied. 

![Screen Shot 2023-01-25 at 11.53.23 AM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/f382599d-8c37-42e8-ad9c-8f9f9511af6d)

This is somewhat unrelated to this issue but the logo is something we will need to include in our config.rb file. 
`AppConfig[:pui_branding_img] = '/assets/images/logo.png'
AppConfig[:pui_branding_img_alt_text] = 'Emory University Libraries Logo'
`

**Comment by maxdmayhew** [comment]
![Screen Shot 2023-01-26 at 3.11.02 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/7ddb664d-aab8-4a8d-8d0f-3473c9b9ab46)

initial setup finished, Submitting PR.

There isn't really a styleguide that was super clear regarding font sizing. Blacklight seems to be super component based with very little extra styling included. The library figma and the site itself conflict in terms in font sizing. Any help would be appreciated. Ready for more tasks :-)

**Comment by erussey** [comment]
Reviewed and seems complete with the caveat that future tickets may require more work in this area if we are missing style elements.
