### ISSUE TITLE
Implement integration with EUL search

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#21]
Amend the Emory libraries search box template (example here: https://libraries.emory.edu/) to search ASpace rather than EmoryFindingAids.  The label for the tab can remain the same, but the search should search ASpace rather than EFA.  

I am unsure if a change to the template will automatically change all the pages that use the search box template.  Please let me know if you need those pages as well.

![Screenshot 2023-06-22 at 12.17.12 PM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/4e65616b-c850-4e23-86cc-b1e0132484ad)

**Comment by CB987** [comment]
This is on production (libraries.emory.edu) now, @erussey.

**Comment by erussey** [comment]
Tested and looks great.  Thanks!
