### ISSUE TITLE
Document webpages that need changed links

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#22]

**Comment by erussey** [comment]
@maxdmayhew @CB987 : Is there some kind of script that we could run to check all the pages within the library domain to look for pages that point to EmoryFindingAids or reference EFA?  Or would finding those be a manual process mitigated by a redirect?

**Comment by CB987** [comment]
I believe the second option is correct.

**Comment by erussey** [comment]
Here's the list of webpages that need to be changed:
https://libraries.emory.edu/tools (plus the tools menu)
https://metadata.emory.edu/systems/finding-aids.html
https://oxford.library.emory.edu/archives/collections
https://search.libraries.emory.edu/
