### ISSUE TITLE
Explore label plug-in

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#25]
Explore effort needed to Customize and configure the Dartmouth label plug-in: https://github.com/dartmouth-dltg/container_management_labels

Labels should display the following fields (centered on label): See example in comments
Institution Name (small)
Repository Name (small)
##space##
Resource identifier (bold)
##space##
Resource Creator name and date
Resource title
##space##
Container type and indicator

Label brands and sizes (staff users should be able to pick the label they want to use):
Avery 3 1/3" x 4" (6 labels/sheet)
Avery 2" x 4" (10 labels/sheet)

**Comment by erussey** [comment]
![Screen Shot 2023-01-27 at 11.11.59 AM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/1f1aec5c-5032-475a-ae3f-c60d8670dd33)

**Comment by bwatson78** [comment]
Reading through the plugin's documentation, it seems like the effort needed to implement this is relatively little. The challenges that would arise would likely be whether the `agent_name` field is the equivalent to creator, and if not, bringing that value into the plugin, and the addition of a second label size (Avery 2" x 4" seems to be one of the standard sizes already available). There are some other unknowns that will be clearer once we start implementing the plugin.

The action ticket that comes of this Spike should be estimated at an 8.
