### ISSUE TITLE
Create a script to produce a CSV that crosswalks EFA data with ASpace data

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#26]
As data migration is not yet complete, this ticket is to create/test a script for matching and replacing EmoryFindingAids URLs with the new ASpace discovery URLs in pidman.   Note that our ASpace test instance contains pids/identifiers for production data, so the data will match EFA/pidman production (https://pid.emory.edu), not test.

Screenshot of data in pidman:
![Screen Shot 2023-02-22 at 1.39.00 PM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/d85be47f-348e-4268-b98b-e7df2714bbf0)
We need to replace the URI in each of these with a new URI from ASpace that matches the pid.  

ASpace contains pid information for each collection in the EAD location field: ![Screen Shot 2023-02-22 at 1.41.23 PM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/d1770eae-33ef-4928-80eb-d411fbe9c8a9)

I would like the replaced URL to point to the resource in the ASPUI discovery interface, not the staff backend.  So in the example collection in the screenshots above, the URI in pidman would be replaced with: https://emory-dev.lyrasistechnology.org/repositories/2/resources/6992

**Comment by rotated8** [comment]
CSV fields should include
- EAD ID
- EAD Location
- Public URL
- Repository ID
- Collection Identifier (Call Number)
- Title (Name)

**Comment by abelemlih** [comment]
@erussey I sent you an email with .csv generated using the rake task I merged into Curate. Let me know if you have any questions.

**Comment by alexBLR** [comment]
@abelemlih just to make sure.  In the above example, @erussey indicated "the URI in pidman would be replaced with: https://emory-dev.lyrasistechnology.org/repositories/2/resources/6992", our URI are https://archives.libraries.emory.edu/repositories/2/resources/6992... Let me know if it is correct.
