### ISSUE TITLE
Replace EFA pids in Pidman

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#27]
Please make these changes the week of July 3, when I will be able to test them.

Using the script developed in #26, change the primary target URI from the link on the findingaids.library.emory.edu domain to the new link in ArchivesSpace.  Per the script in #26, the new link should point to the resource in the ASPUI discovery interface, not the staff backend.  

Example:
![image.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/9761b4bc-5a29-49ee-a54e-3ac714ab4483)

**Comment by rotated8** [comment]
I noticed the CSV created previously is using dev data, and the resource ids it has are not present in prod. @abelemlih will reproduce the CSV with prod data on Monday, so @alexBLR can work on PidMan later in the week.

Here's [the current CSV](https://emory.sharepoint.com/:x:/r/sites/EmoryUniversityLibraries/Shared%20Documents/Project%20Management%20Office/EUL%20Projects/01%20Active%20Project/ArchivesSpace%20Phase%20II/02%20Planning%20and%20Execution/EFA-to-ASpace-map.csv?d=wd8ddbcf3a2b04c4599e21b5007505507&csf=1&web=1&e=uT2xef)

**Comment by abelemlih** [comment]
@rotated8 I added a new csv with Prod data, please refer to this [file](https://emory.sharepoint.com/:x:/r/sites/EmoryUniversityLibraries/Shared%20Documents/Project%20Management%20Office/EUL%20Projects/01%20Active%20Project/ArchivesSpace%20Phase%20II/02%20Planning%20and%20Execution/EFA-to-ASpace-map.csv?d=w796248ecad8244fa938aeaf78de8cfaa&csf=1&web=1&e=5eIGgy). I also kept the old file for reference purposes (file has suffix `-old`). Feel free to delete it if it is no longer needed. 

@alexBLR I noticed that the Excel online viewer is not displaying all data correctly. I recommend downloading the csv and opening on your machine to ensure all data is displayed correctly.

**Comment by alexBLR** [comment]
@abelemlih everything looks good to me. I will start on this shortly.

**Comment by erussey** [comment]
@alexBLR : Do you need anything else from me?  Just to clarify, I am unclear as to whether we are running the replace in prod pidman or in test.

**Comment by erussey** [comment]
Tested and looks good.  Thanks!
