### ISSUE TITLE
Establish permissions to the ArchivesSpace Test environment

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#3]
This includes the following tasks:

- [x] Verify and add permissions in the AS Test staff interface (https://emory-dev.lyrasistechnology.org/staff) for all project members

- [x] Verify that LTDS users (below) have read/write API access (https://emory-dev.lyrasistechnology.org/staff/api)

**Project members who need access to ASpace staff interface:** 

- Admin access to all repositories: Elizabeth Roke, Collin Brittle, Alex Cooper, Carrie Hintz, Lisa Hamlett, Avery Johnson, Ann Hulton

- Repository manager access to all repositories: Katherine Fisher, Emily Corbin, John Bence, Clare Barton, Max Mayhew, Alex Zotov, Brad Watson, Ayoub Belemlhi, Kaeln Bowater-Skelly, Beth Crompton, Cari Lovins, Doug Goans, Laura Starratt, Gabrielle Dudley, Brandon Wason, Kerry Bowden, Erin Grimes, Rebecca Sherman

**Project members who need read/write API access:**

- Elizabeth Roke, Collin Brittle, Alex Cooper, Lisa Hamlett, Avery Johnson, Ann Hulton, Clare Barton, Max Mayhew, Alex Zotov, Brad Watson, Ayoub Belemlhi, Kaeln Bowater-Skelly, Beth Crompton

**Comment by lisahamlett** [comment]
API access to ArchiveSpace must be approved by stakeholders and documented before it can be provided.
In Box, it was documented at this link: https://emory.app.box.com/file/436076541480
I found the folder where the files are now (https://emory.sharepoint.com/sites/EmoryUniversityLibraries/Shared%20Documents/Forms/Al[…]Implementation&viewid=53dab881-7933-4e17-8139-5c0b1c18992d) but I can't find that file.  If anyone remembers where it is, I'd appreciate that information.

**Comment by erussey** [comment]
@lisahamlett : What documentation do you need?  I'm a little unclear as to the workflow that was previously established here.  Note that we are redoing the permissions structure as a part of this project, so much of what was previously established will be reworked.  This ticket applies only to permissions for test, not prod.

**Comment by lisahamlett** [comment]
When ArchiveSpace was implemented, the senior administrators indicated they wanted API access limited because the API is very powerful and they felt that not everyone should have access to something that they could accidentally use to wipe out the entire database.  As a result, they set up a document where access would be tracked so they could approve this access before it was given.

I have a link in my instructions to the Box file above, but that no longer exists, of course.  I assume it migrated to OneDrive somewhere, but I cannot find it.

**Comment by lisahamlett** [comment]
To be clear: I understand this doesn't matter for test, but I am updating documentation and training, so I'd like to have the correct information so folks are informed.
Access will be set up to test tomorrow.

**Comment by lisahamlett** [comment]
Admin access verified for Elizabeth Roke, Alex Cooper, Carrie Hintz, Lisa Hamlett, Avery Johnson, and Ann Hulton.

@lovinscari, @rotated8, @bwatson78, and @abelemlih have never logged in to ArchiveSpace, so they cannot be given any access until they do.

Ann, Avery, and I are working on access for the rest.  We will update when we are finished.

**Comment by avejohnson** [comment]
@maxdmayhew @alexBLR Also have not logged in, so cannot be given access.

**Comment by lisahamlett** [comment]
I am reminding people to log in as I send them their API logins.  So, the developers will have emails about this.

**Comment by avejohnson** [comment]
Everyone currently with accounts now have repo manager access to: Rose, Health, and Oxford.

**Comment by lisahamlett** [comment]
@bwatson78 logged in, so I gave him permissions to all the repos.

**Comment by lisahamlett** [comment]
API accounts have been created for everyone who needs one.

**Comment by libah** [comment]
Everyone with accounts now how repo manager access to Pitts, EUA and Law.

**Comment by libah** [comment]
Max, Zo, Ayoub, and Cari need to login.

**Comment by lisahamlett** [comment]
Max and Zo have logged in

**Comment by avejohnson** [comment]
Max and Zo given repo manager access to Health, Oxford, and Rose.

**Comment by libah** [comment]
Max and Zo and Ayoub given repo manager access to Pitts, EUA and Law.

**Comment by abelemlih** [comment]
@lisahamlett @libah I was able to log in to ArchiveSpace successfully, thanks for all your help!

**Comment by lisahamlett** [comment]
I have verified you have permissions to the repos.

**Comment by lisahamlett** [comment]
In summary: Everyone on the list has the access requested other than Cari Lovins who cannot be given access until she logs in to the system so ArchiveSpace can retrieve her credentials from Shibboleth.

**Comment by lovinscari** [comment]
@lisahamlett - sorry for the delay. I was able to login to the test environment.

**Comment by lisahamlett** [comment]
@lovinscari Avery is going to add your access now

**Comment by avejohnson** [comment]
@lovinscari you should now have access to all repositories.

**Comment by lisahamlett** [comment]
I just discovered tonight that all of this work is no longer in the test environment. It has all been wiped.
