### ISSUE TITLE
Implement and configure Aeon plug-in

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#33]
NOTE: The Aeon webpages are being configured currently to accept requests from the plug-in.

Implement and configure the [Aeon plug-in.](https://github.com/AtlasSystems/ArchivesSpace-Aeon-Fulfillment-Plugin/tree/prerelease) Atlas manages our Aeon instance and should be able to answer questions we have during implementation.  Documentation is here (see sections titled 5.2): https://support.atlas-sys.com/hc/en-us/articles/4415880384659-ArchivesSpace-Request-Fulfillment-via-Aeon and here: https://support.atlas-sys.com/hc/en-us/articles/15066308952083  

For now, please integrate with testAeon: https://emorytest.aeon.atlas-sys.com/ .  When we move into production, we will need to integrate our Aeon production instance with ASpaceProd.

Some additional configurations we know we need now based on the Aeon documentation:

- enable the :top_container_mode setting

- Enable the :requests_permitted_for_containers_only setting

- We do not need user-defined fields sent to Aeon.

**Comment by tmill29** [comment]
Brad, Ayoub, Elizabeth and Collin to meet on Monday.

**Comment by erussey** [comment]
@abelemlih : The Github link for the new revised Aeon plug-in is here for us to fork: https://github.com/AtlasSystems/ArchivesSpace-Aeon-Fulfillment-Plugin/tree/prerelease

**Comment by abelemlih** [comment]
Request for a new release was submitted to Lyrasis by email. Please refer to the release notes: https://github.com/emory-libraries/aspace-deployment/releases/tag/v2023-04-10

**Comment by abelemlih** [comment]
This ticket has been deployed to Test under v2023-04-10

**Comment by erussey** [comment]
Marking this as done since the plug-in has been implemented.  But a few additional tweaks will be needed in order to test the plug-in with staff/end users.  This is documented in #129.
