### ISSUE TITLE
Post banner in EFA notifying users of the ASpace beta product and timeline for decommissioning.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#38]
**This story should not be implemented until May 24, the go-live date for the public beta release.**

Banner text should read:
Over the summer, Emory University will be migrating EmoryFindingAids to a new and improved discovery interface.  To try it out, visit [https://archives.libraries.emory.edu](https://archives.libraries.emory.edu). We welcome your [feedback](https://emory.libwizard.com/f/ArchivesSpace_Feedback)!  Please note that there may be some periods where the new interface will be unavailable.  EmoryFindingAids will remain available through August 2.

**Comment by tmill29** [comment]
Elizabeth with message Zo when this ticket is ready to be completed.

**Comment by erussey** [comment]
@alexBLR : We are ready for this ticket to be implemented.  Thanks!
