### ISSUE TITLE
Decommission EFA, test EFA and related repositories

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#40]
- [x] SVN repositories-- @alexBLR / @rotated8   determine what is being hosted in SVN repositories.  If the EFA repositories are the only one, we may be able to decommission the entire SVN server/server mount.
- [x] mySQL db-- @rotated8 contact OIT for dumps from EFA prod
- [x] @alexBLR / @rotated8  / @kbowaterskelly  Investigate if there are other dependent applications for EFA that might be decommissioned.  We have established through discussion that Fedora, RabbitMQ, eXist, SOLR needs to remain in place as-is.  Need to investigate if there are changes that need to be made to celery.

Decommissioning steps

- [x] Turn off Apache for EFA and EFATest

- [x] CB will contact OIT for dumps from SQL db

- [x] Add the backups for the SQL data to the repository with the SVN backup data

**Comment by erussey** [comment]
Includes the following systems:

- [ ] EFA prod

- [ ] EFA test

- [ ] EFA SVN prod

- [ ] EFA SVN test

**Comment by tmill29** [comment]
Work on this ticket can begin on July 26th or after, once Elizabeth returns from vacation.

**Comment by kbowaterskelly** [comment]
/home/httpd/sites/findingaids/svn-working-dir - "SVN Working Directory"

**Comment by tmill29** [comment]
Torri to check in with Collin and Kaeln on Wednesday the 9th.

**Comment by kbowaterskelly** [comment]
Blocked currently due to #39

**Comment by erussey** [comment]
@rotated8 @kbowaterskelly : while turning off EFA is blocked for now, can we resolve the final task on this ticket to investigate what else needs to be turned off other than the web application itself?  (i.e. celery?)
