### ISSUE TITLE
Core Systems training tasks

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#42]
Please read and familiarize yourself with the ASpace technical documentation.  When you have finish your review of the technical documentation, please check the box beside your name to indicate that you have completed this work.

- [x] Alex Cooper

- [x] Ann

- [x] Avery

- [x] Lisa

Much of the ASpace documentation is behind a firewall in the [ArchivesSpace Help Center](https://archivesspace.atlassian.net/wiki/spaces/ArchivesSpaceUserManual/overview), which is located in the ArchivesSpace Confluence space. If you do not have access, but you have an Atlassian Confluence account using your emory.edu email address, please let @erussey know.  Otherwise, you will need to create an account using your emory.edu email address on the the [Atlassian Confluence Account Creation Page](https://id.atlassian.com/signup?continue=https%3A%2F%2Farchivesspace.atlassian.net%2Flogin%3FredirectCount%3D1%26dest-url%3D%252Fwiki%252Fdiscover%252Fall-updates%26application%3Dconfluence&application=confluence). 

**Other ASpace documentation:**

- [ArchivesSpace database structure overview
](https://archivesspace.github.io/tech-docs/architecture/backend/database.html)
- [ArchivesSpace Technical overview](https://archivesspace.github.io/tech-docs/readme_evaluate.html)
**note that because our instance is hosted, we only have access to the API.  Server-side configurations are made via a request to the Lyrasis sysadmin

**Training videos** (note that some of this is geared towards non-developers and may be somewhat out of date due to subsequent software releases):

- [Configuring your ASpace Implementation](https://youtu.be/EUmeSQK-l0s) (40:28)

- [ArchivesSpace overview](https://youtu.be/Pb359W6IsnA) (51:06)

**Comment by avejohnson** [comment]
I have gone through everything outside of the AS Help Center. For whatever reason my original account creation did not take, so I am still waiting on access. 
Edit: I have access now, will go through remaining materials up until the 11am meeting.
