### ISSUE TITLE
Verify permissions to the ArchivesSpace Test API

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#45]
Please verify that you can access the ASpace Test API.  You should use their ASpace username and password to login through the API.  You'll then get a session token to use.  Please verify access to https://emory-dev.lyrasistechnology.org/staff/api with a browser from campus or a VPN. :

- [x] Elizabeth Roke

- [x] Collin Brittle

- [x] Alex Cooper, Lisa Hamlett

- [x] Avery Johnson

- [x] Ann Hulton

- [x] Clare Barton

- [x] Max Mayhew

- [x] Alex Zotov

- [x] Brad Watson

- [x] Ayoub Belemlhi

- [x] Kaeln Bowater-Skelly

- [x] Beth Crompton

**Comment by jcrompton42** [comment]
I get error 403 forbidden.

**Comment by lisahamlett** [comment]
@jcrompton42 That is because I have not yet created your accounts.
You cannot use your emory logins for the API in ArchiveSpace because the API interface is not behind Shibboleth.  You will need an API access login, which Ann, Avery, and I will be working on tomorrow.

**Comment by lisahamlett** [comment]
I have created API accounts for all of these folks and verified they have access.
I have sent each user their login and password.

**Comment by lisahamlett** [comment]
I just discovered tonight that all of this work is no longer in the test environment. It has all been wiped.
