### ISSUE TITLE
Verify permissions to the ArchivesSpace Test environment

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#48]
Please verify that you can log in through Shibboleth to the ArchivesSpace Test environment. Go to https://emory-dev.lyrasistechnology.org/staff/ and log-in using the Dev Site Emory Sign In option (upper right hand corner).  You should see a pink bar in the site, indicating that you are in the test and not production system.

- [x] Elizabeth Roke

- [x] Collin Brittle

- [x] Alex Cooper

- [x] Carrie Hintz

- [x] Lisa Hamlett

- [x] Avery Johnson

- [x] Ann Hulton

- [x] Katherine Fisher

- [x] Emily Corbin

- [x] John Bence

- [x] Ashley Stevens

- [x] Clare Barton

- [x] Max Mayhew

- [x] Alex Zotov

- [x] Brad Watson

- [x] Ayoub Belemlhi

- [x] Kaeln Bowater-Skelly

- [x] Beth Crompton

- [x] Cari Lovins

- [x] Doug Goans

- [x] Laura Starratt

- [x] Gabrielle Dudley

- [x] Brandon Wason

- [x] Kerry Bowden

- [x] Erin Grimes

- [x] Rebecca Sherman

**Comment by tmill29** [comment]
The maximum number of assignees is ten people.

**Comment by lisahamlett** [comment]
Everyone on the list has permissions except Cari Lovins, as we cannot add permissions until she logs into ArchiveSpace so ArchiveSpace can retrieve her credentials from Shibboleth.

**Comment by lovinscari** [comment]
I was able to login. I am unsure if the message "You do not have access to any Repositories. Please contact your System Administrator to request access." is expected.

**Comment by avejohnson** [comment]
@lovinscari I'll add your repo access now.

**Comment by lisahamlett** [comment]
I just discovered tonight that all of this work is no longer in the test environment.  It has all been wiped.
