### ISSUE TITLE
Create ArchivesSpace "about" page.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#63]
We need to add an about page similar to the [one for Aeon](https://emorytest.aeon.atlas-sys.com/aeon/aeon.dll?Action=10&Form=1).

Please work with Lyrasis to determine whether this page can live within the ArchivesSpace webpages with a header/footer that matches other pages on the site.

The text on the page should be as follows:

**About ArchivesSpace**
ArchivesSpace is an open source archives information management application designed to manage information about special collections material such as archives, manuscripts and digital objects. 

ArchivesSpace provides centralized access to detailed descriptions of archival and manuscript collections held in various repositories at Emory.  Finding aids describe our unique primary resources and help researchers determine if collections contain material of interest to them and exactly where that material is located. ArchivesSpace includes finding aids for both processed and unprocessed collections at the [Stuart A. Rose Manuscript, Archives, and Rare Book Library,](https://libraries.emory.edu/rose) the [Emory University Archives](https://libraries.emory.edu/rose), [Oxford College Archives](https://oxford.library.emory.edu/), [Woodruff Health Sciences Center Library Historical Collections](https://libraries.emory.edu/health), [Pitts Theology Library Special Collections and Archives](https://pitts.emory.edu/) and the [Emory Law School Archives](http://library.law.emory.edu/).

**Accessibility**

Emory Libraries is committed to the principles of universal design and strives to provide equitable services online and in our spaces. We assess and enhance the usability and accessibility of our digital interfaces on an ongoing basis, and use Section 508 of the Rehabilitation Act and current WCAG AA standards as benchmarks. For further information, please use our feedback form or consult Emory’s Department of Accessibility Services.

**Questions, Help, and Feedback**

Please visit our [Help & Contacts page](https://libraries.emory.edu/contact/ask-librarian) for more information about Emory Libraries collections and access.

**Comment by CB987** [comment]
![Screen Shot 2023-01-23 at 3.27.15 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/3853ba6a-5c0c-4fea-8f77-7fef5353ea51)
without any styling, obvs. just basic static page.

**Comment by erussey** [comment]
@CB987 I see two issues in the above: In the second paragraph there is a stray \ in the second sentence: "Finding\aids describe".  There's also an underline under Stuart A. Rose Manuscript (the link in the same paragraph).  Not sure if this is due to the screenshot or if it's an error.  The rest looks great for basic text; styling to follow https://app.zenhub.com/workspaces/archivesspace-63122393d517dc001c3ceb07/issues/gh/emory-libraries/aspace/18 I assume.

**Comment by CB987** [comment]
Got it! Will fix those and yes, styling incoming. Thanks!

**Comment by CB987** [comment]
Fixed the stray \.
You are right about the underlining; it was just bc of the screenshot. Those links will each underline on hover, but none of them are underlined if not.

**Comment by CB987** [comment]
![Screen Shot 2023-01-27 at 11.42.19 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/19a11d0a-21db-4eb7-8b1c-1751a96c0732)

i was playing with fonts and colors so ignore those lol

**Comment by erussey** [comment]
The text looks good.  Thanks.
