### ISSUE TITLE
Create a help/FAQ page 

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#64]
We need to add an help page similar to the one for [LibrarySearch](https://search.libraries.emory.edu/help).  It should be linked from the help button in the ASpace header.

The text on the page should match the styling of the Library search help page.  

**ArchivesSpace**  

ArchivesSpace allows you to search for and request manuscript and archive materials from across the Emory Libraries using ArchivesSpace.  

In addition to ArchivesSpace, material from Emory’s special collections can be found using other search portals. Search Emory Libraries’ catalog for rare books, periodicals, maps, and other printed material using Library Search.  

Emory Digital Collections includes digitized material from Emory Libraries collections and Aviary contains audiovisual material.  

 

**ArchivesSpace Search Tips** 

The add row feature (+ icon) will let you construct a more complex search by adding additional search parameters and allowing you to apply And, Or, or Not operators to your search.  

To search an exact phrase, put quotation marks around the phrase.  

Searches are not case sensitive. 

An asterisk can use used as a wildcard character, so a search for librar* will give you results for library, libraries, librarian, etc. 

To browse the collections by Emory Library, Collection title, Subjects, or Names click on the category above the search bar.  

A reminder that ArchivesSpace searches words and phrases used in the finding aids that describe collections, not the words and phrases that appear in documents in the collections themselves. ArchivesSpace only searches finding aids for archives and mansuscripts, it does not search rare books. 

 

**How to request materials** 

For manuscripts and archives collections, use the request button next to the material you would like to request in the “Finding Aid View” tab of the collection description. For printed materials found via Library Search, use the request button in the catalog record to access the request system. Once you have initiated a request you will be prompted to either create a Special Collections Request account or login to and existing one.  

 

**Special Collections Request account** 

You can register, request materials, and make an appointment via your Special Collections Request Account. Anyone is welcome to use Emory’s special collections, you do not have to be affiliated with Emory to use our collections or provide a letter of introduction.  

 

 

**Glossary of ArchivesSpace terms**  

 

**Archives** are materials created or received by a person, family, or organization that are preserved because of the enduring value of the information they contain. 

**Collections** are groups of materials assembled by a person, family, organization, or repository. For example, the Salman Rushdie papers is a collection of materials created or used by Salman Rushdie. 

**Containers** are anything that houses or stores archival materials such as a box or a folder. 

**Digital records** are born-digital and digitized materials. Some of these may be available online, but donor restrictions, copyright considerations, and personal privacy considerations means that many of these materials are only available in our reading rooms. 

**Finding aids** are guides that allow users to discover, understand, and access archival collections. Finding aids describe the creation, arrangement, content, and context of archival materials. 

**Names** are the people, families, and organizations that create archival materials. 

**Repositories** are institutions that hold archival materials, here at Emory they are the different Libraries that contain archives and manuscript materials. 

**Series** are sets of material within a collection that either were created as part of the same activity (like files related to someone’s work on a committee) or are of the same type (like correspondence files or speech files).  

**Subjects** record the main topics that archival collections are about. Subjects also include places and the formats of materials. 

 

**Copyright/Using and publishing from collections** 

Researchers should be aware that the copyright law of the United States (Title 17, USC) provides protection for unpublished materials as well as for published works.  It is your responsibility as a researcher to use materials from the collections in a manner that complies with U.S. copyright law. 

Manuscript collections from the 20th and 21st centuries may contain sensitive or private information. Emory University's special collections libraries strive to identify and restrict or remove all private and confidential information in our collections. However, there may be instances where researchers find materials containing private or confidential information. Users of Emory University's special collections libraries must agree to not disclose, make public, or publish in any format confidential information discovered while using our collections.

**Comment by rotated8** [comment]
This ticket does not have any links. Is the expectation for the page to only contain the text above?

**Comment by abelemlih** [comment]
@erussey What route do we want for the help page, '/help' similar to library search?

**Comment by erussey** [comment]
@abelemlih Yes.  I want to follow the standards established in Library Search as much as possible.

**Comment by CB987** [comment]
Search.libraries' Help Page is sections with content that is lists of links, not text, so those section contents are styled differently.  
Do we want titles for the static pages (like search)? 
Styling this page like search...../help also changes the styles on AS' /about page, but they are consistent. 
![Screen Shot 2023-02-24 at 6.29.44 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/54684174-c932-4981-bfdf-154ee711585a)
![Screen Shot 2023-02-24 at 6.30.11 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/cd948c7f-314b-45dc-a1c8-6c1b9b000631)
@erussey let me know if you'd like any other views or changes.

**Comment by erussey** [comment]
@CB987 The above looks ok, but not sure why the first two headers are tabbed over and smaller than the other headers?  Regardless, per our procedure now, I'm doing QA once it's deployed.

**Comment by CB987** [comment]
Sorry, those screenshots made the page appear wonky. Here is a full page screenshot. ![screencapture-localhost-3001-help-2023-02-27-10_53_00.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/0020bfab-06ba-4708-b3f2-6f5abbc95bd3)

**Comment by erussey** [comment]
I am realizing that the links from the archivist draft of the help page text didn't make it over.  Can those be added?  See: https://emory.sharepoint.com/:w:/s/EmoryUniversityLibraries/EX4L_V29BPtCjtvcbaN0WGEBq7NC06snp1XvwWM3E0eLdg?e=uPp2Jh

**Comment by maxdmayhew** [comment]
PR submitted
