### ISSUE TITLE
Determine workflows for developing plug-ins for ASpace discovery layer

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#67]
Determine methodologies, processes, procedures, and workflows for making changes to Emory's ASpace configurations for the discovery interface.  This includes:

- Methodologies for separating prod and test environments

- Creating repositories for Emory-contributed plug-in code

- Adding the configuration files to the Emory repositories to make/track changes

- Process for making code/configuration changes and communicating changes with Lyrasis for implementation

[Minutes from a Lyrasis meeting related to this issue](https://emory.sharepoint.com/:w:/s/EmoryUniversityLibraries/EQOKBcPOfdFGgbI9X6WCwDcByc3yRq3_3nbVjevvXbb-_w?e=oNqhUu)

A few Github examples that we can follow:
https://bitbucket.org/uvaub/archivesspace-pui-plugin-ub.git
https://bitbucket.org/rubinghm/ubl_aanpassing_archivespasce_ubaplugin.git 
https://github.com/psuscl/pennstate_pui_customizations.git 
https://github.com/YaleArchivesSpace 

Please document high level workflows and repository locations and communicate those with @erussey so they can be added to the ASpace confluence site.

**Comment by rotated8** [comment]
For deployment we will use our standard operating procedure- we will notify stakeholders and get lazy consensus before a deploy to the testing site, and get explicit consensus before a deploy to production. Deploys will be handled by recording their details (config file changes and plugin versions) in our [aspace-deployment repository](https://github.com/emory-libraries/aspace-deployment), and then emailing those details to Lyrasis.

We will create new repositories for plugins as the need arises. Each plugin should have its own unique function that separates it from the others. For now, we are starting with a plugin for our [static pages and theming](https://github.com/emory-libraries/aspace_static_plugins).
