### ISSUE TITLE
Add repository information for all repositories

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#69]
Please add address, email, website, and phone number for all repositories to the repository information in the ASpace backend ("manage repositories").  Note that in the test system currently, there are duplicate repositories with a -2 appended; this information is applicable to the non-2 repositories. 

- Stuart A. Rose Manuscript, Archives, and Rare Book Library

**Repository name**: Stuart A. Rose Manuscript, Archives, and Rare Book Library
**Parent institution**: Emory University Libraries
**Website**: https://libraries.emory.edu/rose
**Contact information**: 540 Asbury Circle, Atlanta, GA 30322
**Phone number**: 404-727-6887
**Email address**: rose.library@emory.edu

- Emory University Archives

**Repository name**: Emory University Archives
**Parent institution**: Stuart A. Rose Manuscript, Archives, and Rare Book Library
**Website**: https://libraries.emory.edu/rose
**Contact information**: 540 Asbury Circle, Atlanta, GA 30322
**Phone number**: 404-727-6887
**Email address**: rose.library@emory.edu

- Oxford College Archives

**Repository name**: Oxford College Archives
**Parent institution**: Oxford College Library, Oxford College of Emory University
**Website**: https://oxford.library.emory.edu/special-collections
**Contact information**: 801 Emory Street Oxford, GA 30054
**Phone number**: 770-784-8380
**Email address**: oxarchives@listserv.cc.emory.edu

- Woodruff Health Sciences Center Library Historical Collections

**Repository name**: Woodruff Health Sciences Library Historical Collections
**Parent institution**: Woodruff Health Sciences Library
**Website**: https://libraries.emory.edu/health/using-library/historical-collections
**Contact information**: 1462 Clifton Road NE Atlanta, GA 30322
**Phone number**: 404-727-5819
**Email address**: historical.collections@emory.edu

- Pitts Theology Library Special Collections and Archives

**Repository name**: Pitts Special Collections and Archives
**Parent institution**: Pitts Theology Library
**Website**: https://pitts.emory.edu/collections/special-collections
**Contact information**: 1531 Dickey Dr. #560 Atlanta, GA 30322
**Phone number**: 404-727-1223
**Email address**: pittssc@emory.edu

- Emory Law School Archives 

**Repository name**: Emory Law Archives
**Parent institution**: MacMillan Law Library
**Website**: https://library.law.emory.edu/collections/archives-and-rare-books.html
**Contact information**: 1301 Clifton Road Atlanta, GA 30322
**Phone number**: 404-727-0059
**Email address**:  lawarchives@emory.edu

**Comment by avejohnson** [comment]
Address, email, website, and phone number have been added to all repositories.
