### ISSUE TITLE
Explore Dynamic Admin Banner

### ISSUE THREAD

**Issue by tmill29** [emory-libraries/aspace#72]
Review dynamic banner for PUI and admin

**Comment by abelemlih** [comment]
Hi @erussey  and @rotated8, I looked into the ability to dynamically edit the admin banner for the ArchivesSpace instance, and while there is a way to add a migration through a plugin, I am just not sure how robust that solution is. Running a migration through a plugin on local does not provide useful feedback when things fail, and I am a bit worried about future cases where any ArchiveSpace updates introduce changes or migrations that could impact our data. 

I wanted to get your feedback on the following. These are the possible solutions with respect to setting a banner:

1- Setup our own banner through our plugin or fork the archivesspace plugin and modify it based on our business needs. This solution will involve a deploy each time we want to enable and display the banner.
2- Setup the banner through the plugin and add Javascript Code that pulls the banner data using an API. We could store the banner data in our own servers, Firebase, or some other solution. Building an external API to host this data would require us to maintain it, and build an admin interface to add/edit the data.
3- Setup the banner through the plugin and save the banner data in the Archivesspace instance itself. This would require storing the banner data in a custom table we add through a migration in the plugin. As I mentioned earlier, this solution will involve adding a migration through the plugin, which I am not sure is robust and handled gracefully through the Archivesspace enviroment. I am mostly worried about any possible scenariors where failing to retrieve the banner data or the migration in the plugin causes the Archivesspace deployments or the front page load to fail.

Please let me know which of these solutions you want to proceed forward with. I will implement #20 based on the choice we make this in this ticket. Thanks!

**Comment by erussey** [comment]
Thanks for exploring these options @abelemlih .  I'm worried that option 2 and 3 are difficult to maintain, or at least require another dependency to do so.  Let's stick with option 1 for now since I suspect we will usually have some lead time for maintenance windows.  It would be helpful to have the ability to set up the banner on the public side, the admin side, or both.  @rotated8 can you confirm the process for requesting a banner?  Would it be an SN ticket?

**Comment by abelemlih** [comment]
@erussey I will set up the banner for both the public and admin sides.

**Comment by tmill29** [comment]
@rotated8 confirmed this will be a SN ticket to request a banner.
