### ISSUE TITLE
Customize search results pages

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#73]
Search results pages appear throughout the site:
https://emory-dev.lyrasistechnology.org/repositories/resources
https://emory-dev.lyrasistechnology.org/objects?limit=digital_object
https://emory-dev.lyrasistechnology.org/agents
(there may be others...everywhere there is a list of results + a filter option)

For all pages with a filter:
- Change the header on the filter options to be "Limit your search"

**Comment by maxdmayhew** [comment]
![Screen Shot 2023-02-14 at 11.27.08 AM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/a25d0deb-8ce8-418b-a943-6db6a1134d3a)

all pages updated.

This could have been a 2. Sorry!
