### ISSUE TITLE
Customize admin login page

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#74]
Please customize the admin login page.  See wireframe in comments: 
 

- Remove the local sign-in option

- Add the following text:
Header: Welcome to Emory's ArchivesSpace
Text: ArchivesSpace is the repository of record for all archival and manuscript collections held by Emory University's special collections repositories.  Oversight for policies around ArchivesSpace and for user training is managed by the Archival Description subcommittee of the [Metadata Policy Committee](https://libnet.libraries.emory.edu/metadata).  To create an account in ArchivesSpace, please contact the ArchivesSpace administrator at your library.  To report problems or issues, please submit a ticket to coreserviceshelp@emory.edu . 

- Add the Emory Library logo

- Customize text in footer (does not need to have the grey fill in the box as in wireframe)

**Comment by erussey** [comment]
Would it be helpful to add the version number? Or would that be too much work to keep updated?

**Comment by erussey** [comment]
Wireframe:[https://app.zenhub.com/files/531984195/49df319d-adf4-4d37-85a1-a4bb663c401b/download](https://app.zenhub.com/files/531984195/49df319d-adf4-4d37-85a1-a4bb663c401b/download)

**Comment by rotated8** [comment]
![Screenshot_20230223_011718.png](https://images.zenhubusercontent.com/544fb8857c6ccc6277a5b44e/7f391ba4-0d40-40a1-8166-0dedeb6f37cd)

Kinda like the above, but better.

![oauth-flow.png](https://images.zenhubusercontent.com/544fb8857c6ccc6277a5b44e/7d84a2ec-684b-482a-878f-2efefd03d6d7)

Inspired by the above.

**Comment by maxdmayhew** [comment]
![Screen Shot 2023-03-02 at 5.41.27 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/f3fecff4-a4a8-476e-8a8c-680434a9fee6)

PR submitted

**Comment by erussey** [comment]
@maxdmayhew : Can we add in the text in the original ticket:  Right now it's hard to tell what application this is without any mention of ASpace.

Header: Welcome to Emory's ArchivesSpace

Text: ArchivesSpace is the repository of record for all archival and manuscript collections held by Emory University's special collections repositories. Oversight for policies around ArchivesSpace and for user training is managed by the Archival Description subcommittee of the Metadata Policy Committee. To create a staff account in ArchivesSpace, please contact the ArchivesSpace administrator at your library. To report problems or issues, please submit a ticket to coreserviceshelp@emory.edu .

**Comment by erussey** [comment]
Looks good with the caveat that the header logo is still missing.
