### ISSUE TITLE
Add styling to the test system to notify users they are in the test environment

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#78]
Create signposts in the test system to indicate to users that they are in a test environment.

- Add another line to the top of the title of the system on the public user interface homepage image: 
ArchivesSpace Test Environment 

- Add another line to the top of the title of the admin landing page:
ArchivesSpace Test Environment

- Change the background color of the header on all public pages from white to light blue (happy to consider alternative colors, but would prefer an Emory color and not red or similar, so we can still implement the announcement banner on test pages)

- Change the background color of the header on all staff side pages from blue to light blue (happy to consider alternative colors, but would prefer an Emory color and not red or similar, so we can still implement the announcement banner on test pages)

**Comment by erussey** [comment]
I have requested a production instance of the PUI so we can start configuring test to look like a test system.

**Comment by rotated8** [comment]
TODO:
- [x] Find and conditionally add an appropriate background color for the https://emory-dev.lyrasistechnology.org header, ideally one that works for the PUI and Staff headers
- [x] Find and conditionally add an appropriate background color for the header for local development, ideally one that works for the PUI and Staff headers

**Comment by maxdmayhew** [comment]
I can't really test this until we deploy. We also might want to review the colors today

![Screenshot 2023-03-07 at 6.00.16 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/a0ea02db-1c2a-494b-a606-afe86faf7a17)

![Screenshot 2023-03-07 at 6.01.17 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/33e84404-bcf7-41b4-a85f-e8cdea30c17c)

![Screenshot 2023-03-08 at 11.22.00 AM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/ff75b503-5324-496a-9c18-6eb7dd601078)

![Screenshot 2023-03-08 at 11.22.21 AM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/a021d208-8ed1-42db-bab9-d4536bdbc139)

**Comment by erussey** [comment]
@maxdmayhew : this styling should also appear on the login page (it might be a separate page from the above)?

**Comment by maxdmayhew** [comment]
![Screenshot 2023-03-08 at 1.07.09 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/558b1d71-4630-48b1-be4c-398e84214dd6)
