### ISSUE TITLE
SPIKE: Find the options for the repository landing page

### ISSUE THREAD

**Issue by maxdmayhew** [emory-libraries/aspace#79]
As the title suggests, we need to find what options we have available to us on the repository landing page (and other pages that include the boxes below). We do know we want to hide the classifications. 

Example: https://emory-dev.lyrasistechnology.org/repositories/4

![Screen Shot 2023-01-31 at 12.00.51 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/7042aaaa-ae53-4368-a265-5066daed187a)

**Comment by abelemlih** [comment]
@erussey Based on the [documentation](https://archivesspace.github.io/tech-docs/customization/configuration.html), we can either hide a specific badge (e.g. classification) for all repositories globally, or we can specify which badges to hide for specific repositories. 

```ruby
# add to config.rb
AppConfig[:pui_hide][:classification_badge] = true
```


Below is an example from my local environment where I hide the "classification" badge globally:

![image.png](https://images.zenhubusercontent.com/6151f04e7e6954612001d8f9/8926d09d-7491-4290-801b-8a770a911c1e)

@erussey could you please create a ticket where you specify which badges to hide globally? Once we have specific requirements for repositories, we can hide specific badges for each repository individually.
