### ISSUE TITLE
Implement label plug-in

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#80]
Customize and configure the Dartmouth label plug-in: https://github.com/dartmouth-dltg/container_management_labels

Labels should display the following fields (centered on label): See example in comments
Institution Name (small)
Repository Name (small)
##space##
Resource identifier (bold)
##space##
Resource Creator name and date (this is an Agent with role=creator)
Resource title
##space##
Container type and indicator

Label brands and sizes (staff users should be able to pick the label they want to use):
Avery 3 1/3" x 4" (6 labels/sheet)
Avery 2" x 4" (10 labels/sheet)
**Margins will have to be smaller and spaces will have to be smaller for the 3 1/3" x 4"

See related [ticket #25](https://app.zenhub.com/workspaces/archivesspace-63122393d517dc001c3ceb07/issues/gh/emory-libraries/aspace/25)

**Comment by erussey** [comment]
![Screen Shot 2023-01-27 at 11.11.59 AM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/1f1aec5c-5032-475a-ae3f-c60d8670dd33)

**Comment by erussey** [comment]
I'm not entirely sure how the document for printing is created, but I can send along a document with margins that we'll need for each label type above.

**Comment by bwatson78** [comment]
The reason for this estimate increase is because a simple implementation isn't producing the expected labels, but a chain of errors that seem to be related to some Rails/Ruby upgrade.

**Comment by bwatson78** [comment]
The plugin has been forked into our Github and customized, located here: https://github.com/emory-libraries/container_management_labels

The PR to initialize/incorporate the plugin: https://github.com/emory-libraries/aspace-deployment/pull/4

It appears that all of the values listed above must be populated in order for the labels to build and deliver. The litany of errors I received were based upon missing values in containers that were provided by the the ArchiveSpace application. When I chose a Container that had a Collection associated with it and all variables present, it formed correctly.

If we expect to create labels for Containers that do not have all of these values populated, we may want to create further issues to protect against empty data and associations.

**Comment by bwatson78** [comment]
[https://app.zenhub.com/files/531984195/cab988c4-7fd8-4061-a958-5be246eaad70/download](https://app.zenhub.com/files/531984195/cab988c4-7fd8-4061-a958-5be246eaad70/download)
[https://app.zenhub.com/files/531984195/d1328525-d138-4f03-b2c2-e02bd0466715/download](https://app.zenhub.com/files/531984195/d1328525-d138-4f03-b2c2-e02bd0466715/download)
![Screen Shot 2023-02-13 at 9.42.50 AM.png](https://images.zenhubusercontent.com/5e6f6c00c3241244877b4aea/1039b11d-a140-4097-b813-a6e97c77b054)

**Comment by bwatson78** [comment]
PR merged, just awaiting a deploy to the live environments.

**Comment by erussey** [comment]
@bwatson78 : Obviously, this will have to be tested in the live environment before we can call it done.  But can we adjust what ends up in the label printouts?  The screenshots you provided above do not match the requirements in the original ticket...we'd like to match our current labels as much as possible. So, for instance, I'd like all the text to be the same and not greyed out, no lines, no italics, etc.  Ideally, we'd test this plug-in on our own live data first and then adjust.  Based on the screenshots above of the plug-in in the UI, I think we have all the right data.  It just needs to be displayed on the label differently.

**Comment by maxdmayhew** [comment]
![Screen Shot 2023-02-24 at 11.08.21 AM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/8d14ffde-f2f1-4366-a757-2519ab7c0934)

![Screen Shot 2023-02-24 at 11.07.48 AM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/ac141c6c-275e-455b-8984-c8709d7fc1d9)

There are a few issues with this that I am seeing already. 
- Margins do not seem to apply when printing as seen in the screenshot. 
- Have been unsuccessful in adding a page break after the 10th or 6th label.
- Safari has a strange scaling issue and it may be best for us to not support that browser.

**Comment by maxdmayhew** [comment]
![image.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/2a5992c2-aed0-4840-ae76-02c152052b98)

page breaks seem to be working now. I am thinking that setting the margins manually when printing is going to be our best approach.

**Comment by erussey** [comment]
@maxdmayhew : This may not have been deployed yet?  I'm still seeing old styling in the plug-in output.![Screen Shot 2023-02-28 at 6.27.59 PM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/3eaf3b24-f220-47a0-9551-2d3a4b0ea91e)

**Comment by maxdmayhew** [comment]
I apologize, I apparently never put in a PR for this. I just submitted one and I can see if we can get this deployed sooner than next week?

https://github.com/emory-libraries/container_management_labels/pull/3

**Comment by erussey** [comment]
Here's what I tested:

- prints out a full sheet or less of labels with proper formatting
Somewhat working for Avery22513...the text is drifting from label to label.  I think we need to figure out what the appropriate spacing should be...there's not enough space at the end of the label to keep the next label formatting the same way.
Not working for Avery 5163...looks like the font size needs to be much smaller and needs to fit in a space that is 2" x 4"
- prints out more than a full sheet (1 or more) of labels with proper formatting
Not working for Avery22513...part of the 7th and 8th labels prints on the first page.
Not working for Avery5163...each label sheet contains 10 labels and part of the 9th and 10th labels ends up on the next page

I tried the above both with setting custom margins and using the default.  Both had the same result.

**Comment by erussey** [comment]
As discussed in standup on 3/10, we will do a check in on this ticket at sprint end to see how close we are to resolving issues.  If not complete, we'll put in blocked and revisit in April/May when dev work picks up again.

**Comment by maxdmayhew** [comment]
Need to change the estimate due to the amount of time this is ultimately taking. The changes/updates are fairly straightforward but the issues (like the page drift) that seem to be happening on the printer are a bit odd and will need a bit more time to resolve.

**Comment by erussey** [comment]
@maxdmayhew : The bigger labels you're trying to find a template for are Avery 5164.  The 22513 may be an older version of the same label, but confirmed today that they are using 5164.  So we have two label sizes: 5164 (the bigger ones) and 5163 (the smaller 2x4 ones).

**Comment by maxdmayhew** [comment]
Made various edits to way the layout is handled, PR was just merged a few minutes ago. 

@erussey you can test this after todays deploy. Both 22513 (5164) and 5163 are ready to test.

**Comment by erussey** [comment]
This looks awesome @maxdmayhew !  Thanks so much!
