### ISSUE TITLE
Document LCNAF plug-in in local Emory github repository

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#83]
https://github.com/archivesspace-plugins/lcnaf

The above plug-in has already been implemented in our production and test instances.  Please document/fork into Emory's github repository for Aspace for tracking purposes.

**Comment by bwatson78** [comment]
The fork has been created: https://github.com/emory-libraries/lcnaf

**Comment by erussey** [comment]
@bwatson78 : This plug-in has disappeared from the staff-side UI.  It should look like this (in our previous implementation):
![Screenshot 2023-06-07 at 5.08.11 AM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/169982fd-2bbe-43b6-98f5-52f28dafa6f1)
![Screenshot 2023-06-07 at 5.08.36 AM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/54f1d4ca-20b8-4211-94e7-cf834017f44c)

Is it still installed?  If so, we may need to reach out to Lyrasis about what happened to it.

**Comment by bwatson78** [comment]
@erussey I have sent an email addressing the issue.

**Comment by erussey** [comment]
Moving this issue to new ticket #156 since this is a bug related to implementation of the plug-in, not documentation of its implementation.
