### ISSUE TITLE
Determine how to add the ASpace version number to the footer in the PUI interface

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#84]
The ASpace version number seems to be restricted to specific admin users with special privileges.  We need to add the ASpace version number to the footer in the PUI.  This includes both the ASpace version and the version of Emory's plug-ins and local configurations which will be also tracked in our github releases.

**Comment by rotated8** [comment]
![Screenshot_20230223_012745.png](https://images.zenhubusercontent.com/544fb8857c6ccc6277a5b44e/1e3d9eb8-4ea6-4c2b-b4ce-10c3ba9420ce)

Example changes to the footer to show the ASpace version, and the Plugins version. The plugins version will come from the `config.rb` setting `AppConfig[:emory_plugins_version]` The Plugins version should be manually set and updated in the deployment repository so it can be read into this space in the footer. The plugins version should only be added to the PUI footer.
