### ISSUE TITLE
Add  "populate from ArchivesSpace" button to Curate

### ISSUE THREAD

**Issue by abelemlih** [emory-libraries/aspace#85]
Add a new button to the "add a new collection" page in curate that populates fields in the form from the ASpace API.  

- Button text should read "populate from ArchivesSpace"
- It should include a dropdown that asks for the repository and identifier; this information will be used to query ASpace for the correct collection which needs the id and repo_id.  If the collection is not found, return a message of "collection not found"

Tasks:

- [x] Add "Populate from ArchivesSpace" button

- [x] After button is clicked, display a modal with a dropdown of repositories from ArchivesSpace

- [x] After repository is selected, display a call number field where user enters the call number of the resource they are searching for (exact match is required)

- [x] After call number is entered, display the Aspace resource that matches the search or "collection not found" error message. If no resources match, or more than one resource matches, display error message.

- [x] If resource is selected, populate all data associated with that resource on the collection creation form

- [x] If an error occurred, display error to the user. An error message is included in the response provided by the Aspace controller if any error occurred.

**Comment by erussey** [comment]
ASpace by default uses ISO-639-2b language codes.

**Comment by tmiles2** [comment]
Controlled vocabularies required in Curate: https://docs.google.com/spreadsheets/d/1tm7RDYWVcAWEZuA-lB3cbxxGI4qjn8uCn71X2EJPB50/edit#gid=854442392

**Comment by abelemlih** [comment]
For reference, this is the list I am using to map language, from the Library of Congress: https://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt. It is the list of the ISO-639-2 standard as requested.

**Comment by CB987** [comment]
with resource:
![Screenshot 2023-03-10 at 1.22.45 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/ddf4caa8-004f-47fb-9e10-f26a7bd202ed)
with error:
![Screenshot 2023-03-10 at 1.22.57 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/ec8384e6-3537-4fb8-b1e0-9c12910892af)
with form populated:
![Screenshot 2023-03-10 at 1.22.33 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/7942f95a-1660-491b-8411-af4631230e99)

**Comment by CB987** [comment]
per discussion with Elizabeth, I'm going ahead and doing a PR with the work completed so far. 
All of the ticket requirements have been satisfied, however, currently the fields with mutliple inputs, like subject topics or subject names, are all populating on one line, not triggering multiple line inputs. i will continue to work on that step. 
Work completed: Added Populate from ArchivesSpace button to New Collection form:
![Screenshot 2023-03-13 at 11.24.55 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/43c4a843-3ab0-426b-83cf-acfd147ebc65)

Added modal for archivesSpace population that includes dropdown with repository select, call number input field, and search in ArchivesSpace button:
![Screenshot 2023-03-13 at 11.25.05 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/6df667ba-dc5d-4b4b-8040-7b9bf2409241)

After searching, result from ArchivesSpace is displayed:
![Screenshot 2023-03-13 at 11.25.16 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/03506084-46f5-4698-970c-fdf87dff0d2f)

Or error message is displayed:
![Screenshot 2023-03-13 at 11.25.27 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/7e38d2db-eeda-4c6d-8a82-94b117c80e82)

Finally, the "Populate from ArchivesSpace" button transfers the data into the form inputs:
![Screenshot 2023-03-13 at 11.25.45 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/6f8739fc-8707-4621-b6f9-a9a39071f2e2)

**Comment by CB987** [comment]
![Screenshot 2023-03-14 at 10.41.04 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/3c5fadaa-64d5-4da2-824c-fd37c2a91d03)

**Comment by CB987** [comment]
the PR has been merged, but we need to get the environment variables set to access the api from test and arch.

**Comment by rotated8** [comment]
TODO: Get two emails to use for bot users for pre-prod and prod api access.

**Comment by lisahamlett** [comment]
I cannot set up bot accounts for API access until I have email addresses to link to the accounts.

**Comment by tmill29** [comment]
Collin will reach to Elizabeth and Alex to discuss.

**Comment by rotated8** [comment]
After conversations with @erussey and @AGCooper we're going to create api users under a different ticket.

**Comment by erussey** [comment]
API permissions now set by @lisahamlett , so this ticket should be good to go.  Curate API user defined as: curate_api

**Comment by abelemlih** [comment]
I added the ArchivesSpace environment variables to Test and Arch. I also reached out to Lyrasis regarding API authorization for the two instances. 

Once Test and Arch are authorized to access the Aspace API, the Aspace/Curate integration will be ready for testing.

**Comment by jcrompton42** [comment]
Due to the networking configuration, ec2 instances on test and arch are contacting lyrasis using the nat gateway ip addresses rather than the elastic ips that have been whitelisted. I will work to address this.

**Comment by jcrompton42** [comment]
The ec2 instances are currently deployed in a private subnet. The only way to really make this work I can think of is to stop the instances, create images from them, and redeploy in a public subnet, reallocating the IPs and updating all of our loadbalancer rules. This may take until tomorrow to complete.

**Comment by jcrompton42** [comment]
I have moved both instances to a public subnet and Ayoub has verified this solved the issue. Reassigning.

**Comment by abelemlih** [comment]
This ticket is ready for testing on Curate Test.

**Comment by eporter23** [comment]
Just created this collection in Curate test, and it worked really well! https://curate-test.library.emory.edu/dashboard/collections/389280gbgj-cor?locale=en 
One issue: the required holding_repository was not populated and the form prompted me to fill it in. Since this is a required field, we should make sure it gets populated. 
![Screen Shot 2023-04-07 at 10.34.50 AM.png](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/c7c91515-dac7-4d29-945d-1a70e85124af)

**Comment by CB987** [comment]
Hmmm, that field is included in what's supposed to be pulled over:
`document.getElementById('collection_holding_repository').value = result_success.repository.holding_repository;`
I will check into why it isn't.

**Comment by CB987** [comment]
For that particular item, Rose Manuscript No. 892, the data object doesn't include a value for the holding repository. 
`{"repository":{"repository_id":"7","name":"Stuart A. Rose Manuscript, Archives, and Rare Book Library\r\n","administrative_unit":"","holding_repository":"","institution":"Emory University","contact_information":"Stuart A. Rose Manuscript, Archives, and Rare Book Library\nEmory University Libraries\n540 Asbury Circle\nAtlanta, Georgia, 30322\nrose.library@emory.edu\n404-727-6887"},"resource":{"resource_id":"3432","title":"William Levi Dawson papers","description":"Papers of William Levi Dawson, African American composer, conductor, and educator from Anniston, Alabama, including correspondence, original scores of Dawson's works, personal and family papers, photographs, audio visual materials, and printed material.","creator":["Dawson, William Levi, 1899-1990."],"uri":"/repositories/7/resources/3432","call_number":"Manuscript Collection No. 892","primary_language":"English","subject_topics":["African American choral conductors.","African American composers.","African American conductors.","African American musicians.","African American students.","African American universities and colleges--Alabama.","African American women.","African Americans--Education (Higher)--Alabama.","African Americans--Music.","Copyright--United States.","Music publishing.","Spirituals (Songs)"],"subject_names":["Dawson, William Levi, 1899-1990.","Ellison, Ralph.","Krasilovsky, M. William.","Spady, James G.","Stokowski, Leopold, 1882-1977.","Fisk University.","Tuskegee Institute.","Tuskegee Institute. Choir.","Tuskegee Normal and Industrial Institute.","Tuskegee University."],"subject_geo":["Africa--Description and travel."],"subject_time_periods":[],"system_of_record_id":"aspace:/repositories/7/resources/3432","finding_aid_link":"https://archives-test.libraries.emory.edu/repositories/7/resources/3432"}}`
So, that explains why it isn't populating.

**Comment by eporter23** [comment]
Thanks @CB987, I'll try another example and see how it goes.

**Comment by eporter23** [comment]
@CB987 I tried a different collection and the same thing happened. I'll follow up with @erussey to see what may be happening on the data side.

**Comment by erussey** [comment]
@eporter23 : We discovered a dependency with whitespaces and mapping tables.  The devs are going to go back and change the mapping slightly so ASpace is only sending over an identifier from the repository to map to Curate data rather than pulling over the text to populate the repository fields (and it not matching what Curate expects).

**Comment by erussey** [comment]
@eporter23 : This ticket should be ready to test again.  @abelemlih fixed the missing holding repository information.  You can test with Dawson again (Manuscript No. 892) as well as a Health collection (Manuscript Collection No. 027), and an EUA collection with a slightly different call number (Series No. 234).

**Comment by erussey** [comment]
See bug fix to the above in #127.

**Comment by eporter23** [comment]
These appear to have all populated successfully:
Dawson: https://curate-test.library.emory.edu/dashboard/collections/5462547dkb-cor?locale=en 
Health: https://curate-test.library.emory.edu/dashboard/collections/590dv41p3c-cor?locale=en
EUA: https://curate-test.library.emory.edu/dashboard/collections/6386hdr84d-cor?locale=en
