### ISSUE TITLE
Update the PUI footer version information

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#86]
Implementation for #84.

![Screenshot_20230223_012745.png](https://images.zenhubusercontent.com/544fb8857c6ccc6277a5b44e/cf38ce45-97b9-4f03-9bad-360586c50f1d)

Example changes to the footer to show the ASpace version, and the Plugins version. The plugins version will come from the `config.rb` setting `AppConfig[:emory_plugins_version]`. The Plugins version should be manually set and updated in the deployment repository so it can be read into this space in the footer. The plugins version should only be added to the PUI footer.

**Comment by rotated8** [comment]
![Screenshot_20230223_012745.png](https://images.zenhubusercontent.com/544fb8857c6ccc6277a5b44e/66fc1790-64eb-4332-8e0a-4eb418659a5d)

Example changes to the footer to show the ASpace version, and the Plugins version. The plugins version will come from the config.rb setting AppConfig[:emory_plugins_version] The Plugins version should be manually set and updated in the deployment repository so it can be read into this space in the footer. The plugins version should only be added to the PUI footer.

**Comment by maxdmayhew** [comment]
![Screen Shot 2023-02-27 at 10.25.12 AM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/c245b772-0a45-4fa5-92bb-39cf97fbd556)

need to update aspace deploy.

**Comment by maxdmayhew** [comment]
![Screen Shot 2023-02-27 at 10.35.57 AM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/6a3dc08d-79e8-4746-a193-be5ca17f8979)

PRs for both aspace deploy and for the plugin are in
