### ISSUE TITLE
Change staff link to open records from the PUI to open in readonly mode.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#88]

**Comment by erussey** [comment]
The PUI side of the application includes a link to open a record on the staff side ("staff only")

![Screen Shot 2023-02-14 at 9.34.22 AM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/9711da78-9b24-4720-8ee8-a7ad9d96bbb8)

Please change the default configuration to open records in readonly mode rather than edit mode.
See techdocs: AppConfig[:pui_staff_link_mode]

**Comment by bwatson78** [comment]
PR made: https://github.com/emory-libraries/aspace-deployment/pull/10
