### ISSUE TITLE
Adjust ASpace PUI header.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#90]
A couple of corrections to the ASpace PUI header:

- [x] Remove the Request Materials button and link

- [x] Adjust the text font size for the links in the header to match that of Library Search: We had talked about the larger font size, but our personal preference is for it to be smaller.

- [x] Remove Digital Materials from the browse dropdown in the header

**Comment by maxdmayhew** [comment]
PR submitted and merged 
![Screen Shot 2023-03-02 at 12.09.48 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/685f0964-2c7e-492e-8a7a-0fdff9b54e9b)
