### ISSUE TITLE
Request production PUI environment from Lyrasis

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#91]
- [ ] Please request a production PUI environment from Lyrasis.  It should be at this URL: https://emory.lyrasistechnology.org/ .  

- [ ] Request authentication similar to what we have for the ASpace test PUI (would prefer a slightly stronger password than what is in place for test)

**Comment by kbowaterskelly** [comment]
This issue is blocked, per erussey

**Comment by lovinscari** [comment]
@erussey - Can you please update this ticket with the reason for the block?

**Comment by erussey** [comment]
@lovinscari : Our production staff side environment is currently set at this url: https://emory.lyrasistechnology.org/ .  Our test environment has the public user interface (PUI) at https://emory-dev.lyrasistechnology.org/ and the staff side is at the main URL/staff.  In order to match the test and prod environments, we need to move the production staff side application to a new URL: https://emory.lyrasistechnology.org/staff first before we stand up the PUI at https://emory.lyrasistechnology.org/ .  Note that the production staff side environment is an active, production interface, not a test instance.

The overall work needs to happen in this order:

- Schedule maintenance window for prod ArchivesSpace 

- (Lyrasis) Move prod staff application to new URL

- Re-enable Shibboleth for staff production ArchivesSpace instance at new URL

- Test and lift maintenance window for prod staff side ArchivesSpace

- (Lyrasis) Stand up production PUI at new URL with authentication similar to the test PUI (because we are still in alpha release); see requirements in #91

**Comment by erussey** [comment]
@rotated8 : related to this ticket, do we need a spike ticket to talk about the pipeline for releases for the production environments?

**Comment by AGCooper** [comment]
Production PUI looks to be up and functional.
