### ISSUE TITLE
Add jquery to the root of the ASpace application.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#93]
Locally, the jquery that identifies whether the browser is chrome or safari is working correctly. When we deployed the label plugin, we found that those classes weren't populating as expected. The element classes help browser specific styling and would be helpful with the labels appearing as desired. 

Since jquery isn't installed in the base archivesspace application and the labels plugin expects it to be there, it's necessary to add it to the frontend's assets.

**Comment by bwatson78** [comment]
Created [Adds raw jQuery code into assets.](https://github.com/emory-libraries/container_management_labels/pull/2)

**Comment by erussey** [comment]
I assume this is ready to go.  I have no way to test it.  :)
