### ISSUE TITLE
Add AspaceController to Curate

### ISSUE THREAD

**Issue by abelemlih** [emory-libraries/aspace#94]
Backend portion of #85

- [ ]  Add controller with the following methods: #repositories to fetch all repositories, and #find_by_id to fetch a resource by repository id and call number

- [ ] Format Aspace data to fit Curate's business logic. For language, we should use the [ISO 639-2](https://www.loc.gov/standards/iso639-2/ascii_8bits.html) standard. For holding repository and administrative unit, we should use the mapping in this [document](https://docs.google.com/spreadsheets/d/1tm7RDYWVcAWEZuA-lB3cbxxGI4qjn8uCn71X2EJPB50/edit#gid=854442392).

- [ ] Add routes to access Aspace data on Curate: `/aspace/repositories` and `/aspace/find_by_id?repository_id=&call_number=`

**Comment by abelemlih** [comment]
@erussey for testing, please provide a list of call numbers. I will then send you the JSON output for each call number for verification.

**Comment by erussey** [comment]
@abelemlih : Can you send me the following call numbers:
Rose: Manuscript No. 1061, Manuscript No. 754
EUA: Series No. 19
Oxford: Series No. 010, Manuscript Collection No. 035
Pitts: Record Group No. 057

**Comment by abelemlih** [comment]
@erussey I emailed you the testing data, let me know if you have any questions/feedback.

**Comment by erussey** [comment]
@abelemlih : The holding repository information for Series No. 19 example isn't quite right.  The holding_repository for Emory University Archives should be mapped to "Stuart A. Rose Manuscript, Archives, and Rare Book Library"  .  Otherwise looks good.

**Comment by abelemlih** [comment]
@erussey I added the change requested above, please refer to the updated response that I just emailed you. Let me know if you have any additional feedback.
