### ISSUE TITLE
Implement and configure backup database for ASpace

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#95]

**Comment by kbowaterskelly** [comment]
See https://3.basecamp.com/3410311/buckets/29543127/messages/5797916102

I have the private keys but still need to work through implementation with Blake

**Comment by erussey** [comment]
The purpose of these backups is mostly for security reasons and larger failures like entire collections being accidentally deleted.  With that in mind, I would like monthly backups, maintained for a period of 5 years on a rolling basis, so that older backups are deleted past this period.

**Comment by jcrompton42** [comment]
@erussey the database in this case does not contain the actual collection xml files. Are you sure the database is what you want backed up and not the set of xml files? I am attaching an example of the database backup provided so I want to make sure you are requesting a backup of the correct thing :)[https://app.zenhub.com/files/531984195/da918d6d-9315-41f8-a44c-441e18eb73e7/download](https://app.zenhub.com/files/531984195/da918d6d-9315-41f8-a44c-441e18eb73e7/download)

**Comment by erussey** [comment]
@jcrompton42 : My understanding is that the database backup contains all the data from the ASpace database and could be loaded onto a local ASpace instance if necessary.  An XML extract would only contain a partial copy of the data; ASpace also stores data about collection accessions, valuation, donor information and similar, which are not part of the XML. Am I correct in my understanding that the database backup would contain a full extract of all the data in ASpace on a particular date?

**Comment by jcrompton42** [comment]
It contains all the data from the database definitely. However, the database itself is only going to be storing information about the actual data in finding aids, so if an entire collection is deleted, those files won't be in the database. Does that make sense?

**Comment by erussey** [comment]
Yes, makes sense.  That's why we are keeping multiple copies of the backups so that we can go back through time and find the missing object and when it disappeared.  By the way, we wouldn't be using this for an "oops I deleted a collection" scenario, probably.  It would be more like a security/internal theft concern where an archival object (i.e. something valuable) disappeared and we need to track down when/why/who made the change.  So I expect it to be rare that we go to a backup.

**Comment by jcrompton42** [comment]
Got it, just making sure I was backing up what you expected to have! Thanks!

**Comment by erussey** [comment]
I am not sure how to test this, but assuming that if the Core Systems team says it's functional, it is.
