### ISSUE TITLE
Get approval and smartkey for storage of ASpace backup copies.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#96]

**Comment by AGCooper** [comment]
I've received enough information to estimate this as less than a terabyte for a year. I'd suggest implementation as-is of the daily backup Lyrasis has planned and retention of 2 years. This should be less than a hundred dollars a month.

**Comment by jcrompton42** [comment]
Pulling down one database backup from lyrasis, the size of a compressed db dump is almost 10M right now. Overestimating and calling it 50M, that would be 
50 * 12 * 5 = 3000M or 3G of data in S3
If left in standard S3 storage, that would be $0.023 per GB per month 
If I move to glacier storage, that is $0.00099 per GB per month

**Comment by AGCooper** [comment]
Sent this information to Rosalyn for approval.

**Comment by AGCooper** [comment]
Rosalyn responded: " I think that’s in line with what is happening with Drupal so seems good to me." - I take that as approval.
