### ISSUE TITLE
Create readme in aspace-deploy repo of deployment procedures

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#98]
Create a readme document in the [ASpace-deploy repository](https://github.com/emory-libraries/aspace-deployment) that documents the deployment procedures for the application. This includes

- Updating the plugin version number (`AppConfig[:emory_plugins_version]`) in `config.rb` before tagging a release
- How to tag a release and package it for Lyrasis
- Procedures for contacting Lyrasis and confirming the deployment is complete

**Comment by abelemlih** [comment]
@erussey @rotated8 @bwatson78 I opened a PR with documentation on how to deploy a new version of the plugin to ArchivesSpace. Please let me know if there is anything I am missing: https://github.com/emory-libraries/aspace-deployment/pull/11/files

**Comment by abelemlih** [comment]
@erussey The instructions have been approved and merged. Please review the README in the repository and let me know if you have any feedback: https://github.com/emory-libraries/aspace-deployment
